/* UI / persistence adapter. The simulation lives in engine.js. */
'use strict';
const E=Shopshift,$=id=>document.getElementById(id),KEY='shopshift-save-v1';
let game=E.create(),tab='products',supplier=0,muted=false,saveOK=true,toastTimer,confirmAction=null;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(E.validate(parsed))game=parsed;else throw Error('Zapis niezgodny');}}catch{saveOK=false;}
const money=n=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:2,minimumFractionDigits:0}).format(E.round(n))+' zł';
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(KEY,JSON.stringify(game));saveOK=true;}catch{saveOK=false;}$('save-status').textContent=saveOK?'● Postęp zapisany':'○ Zapis niedostępny — eksportuj grę';}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4000);}
function tone(){window.LiveAudio?.play('action');}
function action(fn){try{fn();save();render();tone();}catch(e){toast(e.message);}}
function showDialog(html){$('dialog-body').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();}
function closeDialog(){$('dialog').close();confirmAction=null;}
function go(next){tab=next;render();}
function art(p){let body=p.shape==='jar'?'<rect x="13" y="30" width="46" height="35" rx="9" fill="'+p.color+'"/><rect x="11" y="25" width="50" height="13" rx="4" fill="#f6f6f6"/>':'<rect x="21" y="22" width="29" height="50" rx="8" fill="'+p.color+'"/><rect x="26" y="9" width="19" height="17" rx="3" fill="'+(p.shape==='dropper'?'#5d5d5d':'#f8f8f8')+'"/>'+(p.shape==='pump'?'<path d="M30 10 V5 H49" stroke="#f7f7f7" stroke-width="6" stroke-linecap="round"/>':'');return '<svg viewBox="0 0 72 85" aria-hidden="true">'+body+'<rect x="25" y="41" width="21" height="18" rx="2" fill="#fcfcfc" opacity=".9"/><text x="35.5" y="49" text-anchor="middle" font-size="4" font-family="sans-serif" fill="#6c6c6c">'+p.name.split(' ')[0].toUpperCase()+'</text><path d="M31 53 H40 M33 56 H38" stroke="#ababab" stroke-width=".6"/></svg>';}
function render(){
$('cash').textContent=money(game.cash);$('cash').className=game.cash<0?'negative':'';$('cash-note').textContent=game.cash<0?'Utrata płynności — sprzedaj zapasy lub zacznij od nowa':('Zapasy: '+money(game.stock.reduce((a,b)=>a+b.value,0)));
$('revenue').textContent=money(game.ledger.sales);$('profit').textContent=money(E.profit(game.ledger));$('profit').className=E.profit(game.ledger)<0?'negative':'positive';$('rating').textContent=game.rating.toFixed(1).replace('.',',');$('review-count').textContent=game.ratingCount+' ocen · '+game.shipped+' wysłanych paczek';
$('day-label').textContent='Dzień '+game.day;$('phase-label').textContent={plan:'Przygotowanie sklepu',fulfill:'Pakowanie i wysyłka',report:'Podsumowanie dnia'}[game.phase];
const level=E.LEVELS[game.level];$('warehouse-name').innerHTML=level.name+' <small>'+level.size+'</small>';$('level').textContent='POZIOM 0'+(game.level+1);$('capacity').textContent=E.used(game)+' / '+level.capacity+' szt.';$('capacity-bar').style.width=Math.min(100,E.used(game)/level.capacity*100)+'%';
const waiting=game.orders.filter(o=>o.status==='new').length,packed=game.orders.filter(o=>o.status==='packed').length;
$('order-count').textContent=waiting+packed;$('packing-status').textContent=game.worker?'Magazynier + Ty · '+game.packedToday+' spakowanych':waiting?waiting+' paczek czeka na Ciebie':'Stanowisko gotowe do pracy';$('scene-status').textContent=packed?packed+' paczek czeka na kuriera':waiting?'Nowe zamówienia! Czas pakować.':E.used(game)?'Twoja marka rośnie z każdą paczką':'Czekamy na pierwszą dostawę';$('scene-pack').disabled=!waiting||game.phase!=='fulfill';
const stages=['Kup pierwszą kolekcję','Ustal ceny i kampanię','Spakuj i wyślij zamówienia','Sprawdź zysk i reinwestuj'];const step=game.phase==='report'?4:game.phase==='fulfill'?2:game.tutorial===0?0:1;
$('steps').innerHTML=stages.map((s,i)=>'<li class="'+(i<step?'done':'')+'"><span class="step-num">'+(i<step?'✓':i+1)+'</span>'+s+'</li>').join('');
if(game.phase==='plan'){
$('mission-title').textContent=game.day===1&&game.tutorial===0?'Pierwsza kolekcja':'Czas na kolejny ruch';$('mission-copy').textContent='Kup kosmetyki, ustal ceny i wybierz kampanię. Pieniądze mają pracować na Twój zysk.';$('main-action').textContent=game.tutorial===0?'Kup pierwszy produkt ↗':'Otwórz dzień sprzedaży →';$('action-note').textContent='Koszt dnia: '+money(level.rent+(game.worker?95:0))+' + reklama.';
}else if(game.phase==='fulfill'){
$('mission-title').textContent=waiting?'Zamówienia czekają!':packed?'Kurier już jest.':'Dobra robota.';$('mission-copy').textContent=waiting?'Spakuj produkty przy stanowisku. Dopiero wysłane zamówienie przynosi przychód.':packed?'Przekaż paczki kurierowi, aby zakończyć realizację i otrzymać płatności.':'Sprawdź, ile naprawdę zarobiła Twoja firma. Zamknij dzień i zaplanuj następny.';$('main-action').textContent=waiting?'Spakuj następną paczkę →':packed?'Wyślij paczki →':'Podsumuj dzień →';$('action-note').textContent=waiting+' do pakowania · '+packed+' do wysłania';
}else{$('mission-title').textContent=E.profit(game.ledger)>=0?'Każdy zysk to krok.':'Obrót to nie wszystko.';$('mission-copy').textContent='Wynik dnia: '+money(E.profit(game.ledger))+'. Przejrzyj koszty i podejmij kolejną decyzję. Zwroty mogą pojawić się za 2 dni.';$('main-action').textContent='Rozpocznij dzień '+(game.day+1)+' →';$('action-note').textContent='Kolejny dzień zaczyna się od planowania.';}
$('tip').textContent=game.phase==='fulfill'?'Niewysłane paczki na koniec dnia oznaczają anulowanie i słabszą opinię.':game.day>2?'Zwrot oddaje klientowi całą wpłatę + kosztuje 6 zł. Otwarty kosmetyk nie wraca na regał.':'Cena − zakup − 11 zł realizacji − 2% prowizji. Z tej kwoty finansujesz reklamę i firmę.';
$('footer-log').textContent=game.log[0]||'';document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);if(b.classList.contains('rail-btn'))b.classList.toggle('active',b.dataset.tab===tab);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.tab===tab));});
const renders={products:productsView,orders:ordersView,marketing:marketingView,finance:financeView,growth:growthView,reviews:reviewsView};$('content').innerHTML=renders[tab]();Warehouse.update(game);window.refreshLiveUI?.();
}
function productsView(){return '<div class="section-heading"><div><h3>Twoja kolekcja beauty</h3><p>Fikcyjne produkty. Prawdziwe decyzje. Ustaw cenę sprzedaży i uzupełnij regały.</p></div><select id="supplier" aria-label="Dostawca"><option value="0" '+(supplier===0?'selected':'')+'>Bloom Supply · od ręki · min. 5 szt.</option><option value="1" '+(supplier===1?'selected':'')+'>Luma Labs · jutro · −14% · min. 20 szt.</option></select></div><div class="products">'+E.PRODUCTS.map((p,i)=>{const cost=E.round(p.cost*(supplier===1?.86:1)),margin=game.prices[i]+(game.freeShipping?0:9)-cost-11-(game.prices[i]+(game.freeShipping?0:9))*.02;return '<article class="product" style="--tint:'+p.color+'24"><div class="product-art"><span class="stock-label">'+game.stock[i].qty+' na stanie</span>'+art(p)+'</div><div class="product-info"><h3>'+p.name+'</h3><p>'+p.kind+'</p><div class="price-line"><span>Zakup</span><b>'+money(cost)+'</b></div><label class="price-line">Cena <span><input aria-label="Cena '+p.name+'" class="price-input" type="number" min="5" max="300" step="1" data-price="'+i+'" value="'+game.prices[i]+'" '+(game.phase!=='plan'?'disabled':'')+'> zł</span></label><div class="margin-line '+(margin<0?'negative':'')+'">Po realizacji: '+money(margin)+'/szt.*</div><button class="buy-btn" data-buy="'+i+'" '+(game.phase!=='plan'?'disabled':'')+'>+ Zamów towar</button></div></article>';}).join('')+'</div><div class="inline-help">*Szacunek przy koszcie wybranego dostawcy, przed reklamą, kosztami stałymi i zwrotami. '+(game.deliveries.length?'W drodze: '+game.deliveries.map(d=>d.qty+' × '+E.PRODUCTS[d.index].name+' (dzień '+d.due+')').join(', '):'Zakup zasila zapasy. Koszt towaru obciąży wynik przy wysyłce.')+'</div>';}
function ordersView(){const waiting=game.orders.filter(o=>o.status==='new').length,packed=game.orders.filter(o=>o.status==='packed').length;return '<div class="section-heading"><div><h3>Centrum realizacji</h3><p>'+game.visits+' odwiedzin · '+game.lost+' utraconych zamówień (brak towaru lub limit '+E.LEVELS[game.level].limit+'/dzień)</p></div><div class="actions"><button class="secondary" id="pack-five" '+(!waiting||game.phase!=='fulfill'?'disabled':'')+'>Spakuj do 5 paczek</button><button class="primary" id="ship" '+(!packed||game.phase!=='fulfill'?'disabled':'')+'>Wyślij spakowane ('+packed+')</button>'+(game.phase==='fulfill'?'<button class="secondary" id="finish">Zamknij dzień</button>':'')+'</div></div>'+(game.orders.length?'<div class="orders-list">'+game.orders.map(o=>'<div class="row"><div><strong>#'+o.id+' · '+E.PRODUCTS[o.index].name+'</strong><br><small>1 szt. · '+money(o.price)+(o.freeShipping?' · darmowa dostawa':' + 9 zł dostawa')+'</small></div><span class="pill">'+{new:'Do pakowania',packed:'Spakowane',shipped:'Wysłane',cancelled:'Anulowane'}[o.status]+'</span>'+(o.status==='new'&&game.phase==='fulfill'?'<button class="secondary" data-pack="'+o.id+'">Spakuj →</button>':'')+'</div>').join('')+'</div>':'<div class="empty"><strong>Tu zaczyna się droga każdej paczki.</strong>Po otwarciu dnia zamówienia przychodzą pojedynczo co losowe 20–30 sekund.</div>');}
function marketingView(){return '<div class="section-heading"><div><h3>Daj się odkryć</h3><p>Wybierz jedną kampanię na dzień. Wydatek pobierzemy przy otwarciu sklepu.</p></div></div><div class="campaigns">'+E.CAMPAIGNS.map((a,i)=>'<button class="campaign '+(game.campaign===i?'chosen':'')+'" data-campaign="'+i+'" '+(game.phase!=='plan'?'disabled':'')+'><span>0'+(i+1)+' / '+(game.campaign===i?'WYBRANO':'KAMPANIA')+'</span><strong>'+a.name+'</strong><span>'+money(a.cost)+' / dzień</span><small>Około '+a.visits+' odwiedzin</small></button>').join('')+'</div><label class="checkline"><input id="free-shipping" type="checkbox" '+(game.freeShipping?'checked':'')+' '+(game.phase!=='plan'?'disabled':'')+'> Darmowa dostawa dla klienta (pokrywasz pełny koszt 11 zł zamiast dopłaty 2 zł).</label><p class="note">Reklama sprowadza odwiedzających, nie gwarantuje sprzedaży. Cena i reputacja wpływają na konwersję. Przed dużą kampanią sprawdź marżę, zapasy i limit realizacji. Darmowa dostawa w tym wycinku jest decyzją kosztową — nie zwiększa ruchu.</p>';}
const names={sales:'Przychód z produktów i dostaw',cogs:'Koszt sprzedanych kosmetyków',shipping:'Pakowanie i kurier',fees:'Prowizje płatności · 2%',ads:'Marketing',fixed:'Lokal i wynagrodzenia',refunds:'Zwrot wpłat klientom',returnFees:'Obsługa zwrotów',setup:'Przeprowadzka i wyposażenie'};
function ledger(l){return Object.entries(names).map(([k,n])=>'<div class="ledger-row"><span>'+n+'</span><strong>'+((k!=='sales'&&l[k])?'−':'')+money(l[k])+'</strong></div>').join('')+'<div class="ledger-row total"><span>Zysk / strata</span><strong class="'+(E.profit(l)<0?'negative':'positive')+'">'+money(E.profit(l))+'</strong></div>';}
function financeView(){const h=game.history.slice(-10),max=Math.max(1,...h.map(x=>Math.abs(x.profit)));return '<div class="section-heading"><div><h3>Wynik finansowy · dzień '+game.day+'</h3><p>Obrót pokazuje skalę. Zysk pokazuje, czy biznes działa.</p></div><button class="secondary" id="all-finance">Wynik od początku</button></div><div class="finance-grid"><div>'+ledger(game.ledger)+'</div><div><h3 style="font-size:12px">Zysk w ostatnich dniach</h3><div class="chart">'+(h.length?h.map(x=>'<div class="chart-bar" title="Dzień '+x.day+': '+money(x.profit)+'"><i style="height:'+Math.max(2,Math.abs(x.profit)/max*110)+'px;background:'+(x.profit<0?'#c95a66':'#77777f')+'"></i><small>D'+x.day+'</small><small>'+money(x.profit)+'</small></div>').join(''):'<div class="empty">Zakończ pierwszy dzień, aby zobaczyć historię.</div>')+'</div><div class="note">Gotówka: <b>'+money(game.cash)+'</b><br>Wynik od początku: <b>'+money(E.profit(game.total))+'</b><br>Towar na regałach: '+money(game.stock.reduce((a,b)=>a+b.value,0))+'<br>Towar w dostawie: '+money(game.deliveries.reduce((a,b)=>a+b.value,0))+'<br>Zwroty mogą obciążyć kolejne dni. Rozbudowa jest jednorazowym kosztem; MVP nie symuluje VAT, podatku ani amortyzacji.</div></div></div>';}
function growthView(){return '<div class="section-heading"><div><h3>Więcej miejsca na Twoje ambicje</h3><p>Postęp: '+game.shipped+' zrealizowanych zamówień. Przeprowadzka zwiększa też codzienne koszty.</p></div></div><div class="growth-grid">'+E.LEVELS.map((l,i)=>'<article class="growth-card"><span class="tag">'+(game.level===i?'TWOJA SIEDZIBA':'POZIOM 0'+(i+1))+'</span><h3>'+l.name+'</h3><p>'+l.size+' · '+l.capacity+' szt. magazynu<br>Do '+l.limit+' zamówień / dzień<br>Lokal: '+money(l.rent)+' / dzień<br>'+(i?'Przeprowadzka: '+money(l.upgrade)+'<br>Wymaga '+(i===1?20:100)+' wysłanych paczek':'Twoja historia zaczyna się tutaj.')+'</p>'+(i===game.level+1?'<button class="secondary" id="upgrade" '+(game.phase!=='plan'?'disabled':'')+'>Przenieś firmę ↗</button>':'')+'</article>').join('')+'</div><div class="row"><div><strong>Magazynier · 95 zł / dzień</strong><br><small>Od poziomu 2. Skraca cykl automatycznego pakowania z 16 do 9 sekund. Wysyłkę zlecasz Ty.</small></div><button class="secondary" id="hire" '+(game.level<1||game.phase!=='plan'?'disabled':'')+'>'+(game.worker?'Zakończ współpracę':'Zatrudnij')+'</button></div>';}
function reviewsView(){return '<div class="section-heading"><div><h3>Głos Twoich klientów</h3><p>Średnia '+game.rating.toFixed(2)+' / 5 · reputacja wpływa na ruch w sklepie. Startujesz z 5 ocenami o średniej 4,6.</p></div></div>'+(game.reviews.length?game.reviews.map(r=>'<div class="row"><div><span class="review-stars">'+'★'.repeat(r.stars)+'☆'.repeat(5-r.stars)+'</span><p style="font-size:12px">'+escapeHTML(r.text)+'</p></div><small>Dzień '+r.day+'</small></div>').join(''):'<div class="empty"><strong>Twoja pierwsza opinia jest jeszcze przed Tobą.</strong>Szybka realizacja buduje zaufanie. Anulowanie zamówienia obniża ocenę.</div>');}
function buyDialog(i){const p=E.PRODUCTS[i],qty=supplier===1?20:10;showDialog('<div class="eyebrow">NOWA DOSTAWA</div><h2>'+p.name+'</h2><p>'+(supplier===1?'Luma Labs · 14% taniej · dostawa jutro · minimum 20 sztuk.':'Bloom Supply · dostawa natychmiast · minimum 5 sztuk.')+'</p><label>Liczba sztuk<input id="buy-qty" type="number" min="'+(supplier===1?20:5)+'" max="500" step="1" value="'+qty+'"></label><p id="buy-total"></p><button class="primary" id="confirm-buy" data-index="'+i+'">Zamów i opłać</button>');const update=()=>{$('buy-total').textContent='Wartość zakupu: '+money(Number($('buy-qty').value)*E.round(p.cost*(supplier===1?.86:1)))+' · dostępne '+money(game.cash);};$('buy-qty').addEventListener('input',update);update();}
function packNext(){const o=game.orders.find(o=>o.status==='new');if(o)action(()=>{E.pack(game,o.id);Warehouse.pulse();});}
function finish(){const pending=game.orders.filter(o=>o.status==='new'||o.status==='packed').length,upcoming=E.ensureLive(game).queue.length;if(pending||upcoming){confirmAction=()=>endDay();showDialog('<div class="eyebrow">ZAMKNIĘCIE DNIA</div><h2>Zakończyć sprzedaż?</h2><p>'+pending+' przyjętych zamówień zostanie anulowanych (towar wróci na regały, klienci wystawią ocenę 2/5). Jeszcze '+upcoming+' potencjalnych zamówień nie zdąży nadejść. Reklama nie zostanie zwrócona.</p><button class="primary" id="back-packing">Wróć do sklepu</button><button class="secondary danger" id="confirm-end" style="margin-top:10px">Zamknij dzień mimo to</button>');}else endDay();}
function endDay(){closeDialog();action(()=>{E.close(game);tab='finance';});if(game.phase==='report')showReport();}
function showReport(){const l=game.ledger;showDialog('<div class="eyebrow">DZIEŃ '+game.day+' / ZAMKNIĘTY</div><h2>'+(E.profit(l)>=0?'Twoja praca procentuje.':'Lekcja przedsiębiorczości.')+'</h2><p class="report-big '+(E.profit(l)<0?'negative':'')+'">'+money(E.profit(l))+'</p><p>zysku / straty przy obrocie <b>'+money(l.sales)+'</b>. '+(E.profit(l)<0?'Przed kolejną kampanią sprawdź cenę, koszt pozyskania i liczbę sprzedanych sztuk.':'Zachowaj rezerwę na zwroty i zatowarowanie przed kolejną kampanią.')+'</p><button class="primary" id="report-close">Przejrzyj wynik finansowy →</button>');}
function help(){showDialog('<div class="eyebrow">WITAJ W SHOPSHIFT</div><h2>Od pierwszej paczki do własnej marki.</h2><p>Masz <b>10 000 zł</b>. Na początek zamów po 10 sztuk Dewdrop i Cloud Nine u Bloom Supply. Ustaw własne ceny lub zachowaj sugerowane. W Marketingu wybierz Social starter.</p><p><b>1.</b> Otwórz dzień — kampania przyciągnie klientów.<br><b>2.</b> Zamówienia przychodzą co 20–30 sekund z powiadomieniem i dźwiękiem. Postać sama chodzi po towar i pakuje; możesz jej pomagać.<br><b>3.</b> Wyślij paczki, podsumuj dzień i przejrzyj wszystkie koszty.<br><b>4.</b> Reinvestuj zysk. Po 20 wysyłkach odblokujesz większy magazyn.</p><p>Podczas otwartego dnia czas płynie na żywo. Pauza, otwarte okno opcji i ukryta karta zatrzymują grę. Postęp zapisuje się po każdej akcji w tej przeglądarce. Opcje pozwalają wyeksportować kopię. Rozgrywka działa też bez internetu.</p><button class="primary" id="report-close">Zaczynamy →</button>');}
function options(){showDialog('<div class="eyebrow">TWÓJ SKLEP / OPCJE</div><h2>Postęp pod kontrolą.</h2><p>Zapis jest lokalny dla przeglądarki i adresu gry. Eksport pozwala przenieść sklep na inne urządzenie.</p><div class="actions"><button class="secondary" id="export">Eksportuj zapis</button><button class="secondary" id="import">Importuj zapis</button><input id="import-file" type="file" accept="application/json,.json" hidden></div><p id="import-message"></p><button class="secondary danger" id="reset">Nowa gra</button>');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){go(b.dataset.tab);return;}if(b.dataset.buy!==undefined){buyDialog(Number(b.dataset.buy));return;}if(b.dataset.pack!==undefined){action(()=>{E.pack(game,Number(b.dataset.pack));Warehouse.pulse();});return;}if(b.dataset.campaign!==undefined){action(()=>{if(game.phase!=='plan')throw Error('Kampanię zmienisz jutro.');game.campaign=Number(b.dataset.campaign);});return;}
switch(b.id){case 'main-action':if(game.phase==='plan'){if(game.tutorial===0){go('products');buyDialog(0);}else action(()=>{E.open(game);tab='orders';});}else if(game.phase==='fulfill'){if(game.orders.some(o=>o.status==='packed'))action(()=>{E.ship(game);Warehouse.pulse();});else if(E.ensureLive(game).queue.length||game.orders.some(o=>o.status==='new'))go('orders');else finish();}else action(()=>{E.next(game);tab='products';});break;
case 'scene-pack':packNext();break;case 'pack-five':action(()=>{game.orders.filter(o=>o.status==='new').slice(0,5).forEach(o=>E.pack(game,o.id));Warehouse.pulse();});break;
case 'ship':action(()=>{const n=E.ship(game);Warehouse.pulse();toast('Kurier odebrał '+n+' paczek.');});break;
case 'finish':finish();break;case 'confirm-end':if(confirmAction)confirmAction();break;case 'back-packing':closeDialog();go('orders');break;
case 'confirm-buy':action(()=>{E.buy(game,Number(b.dataset.index),Number($('buy-qty').value),supplier);closeDialog();toast('Zamówienie u dostawcy przyjęte.');});break;
case 'upgrade':action(()=>{E.upgrade(game);toast('Witaj w nowej siedzibie!');});break;case 'hire':action(()=>E.hire(game));break;
case 'help':help();break;case 'menu':options();break;case 'sound':muted=!muted;b.textContent='Dźwięk: '+(muted?'wył.':'wł.');b.setAttribute('aria-label',muted?'Włącz dźwięk':'Wyłącz dźwięk');tone();break;
case 'report-close':closeDialog();break;case 'all-finance':showDialog('<div class="eyebrow">OD PIERWSZEGO DNIA</div><h2>Wynik firmy</h2>'+ledger(game.total));break;
case 'export':{const blob=new Blob([JSON.stringify(game,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SHOPSHIFT-dzien-'+game.day+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Wyeksportowano zapis gry.');break;}
case 'import':$('import-file').click();break;
case 'reset':showDialog('<h2>Zacząć od nowa?</h2><p>To zastąpi bieżący lokalny zapis gry. Wyeksportuj go wcześniej, jeśli chcesz zachować swój sklep.</p><button class="primary danger" id="confirm-reset">Tak, nowa firma</button><button class="secondary" id="report-close">Wróć</button>');break;
case 'confirm-reset':game=E.create();tab='products';save();render();closeDialog();toast('Nowy początek. Powodzenia!');break;}
if(b.classList.contains('dialog-close'))closeDialog();});
document.addEventListener('change',async e=>{const el=e.target;if(el.dataset.price!==undefined)action(()=>E.price(game,Number(el.dataset.price),Number(el.value)));if(el.id==='supplier'){supplier=Number(el.value);render();}if(el.id==='free-shipping')action(()=>{if(game.phase==='plan')game.freeShipping=el.checked;});if(el.id==='import-file'&&el.files[0]){try{if(el.files[0].size>2000000)throw Error('Plik zapisu jest za duży.');const data=JSON.parse(await el.files[0].text());if(!E.validate(data))throw Error('Nieprawidłowy lub niezgodny zapis.');game=data;save();render();closeDialog();toast('Wczytano dzień '+game.day+'.');}catch(err){$('import-message').textContent=err.message;}}});
$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
render();if(!saveOK)toast('Nie udało się odczytać zapisu. Użyj opcji eksportu, aby zabezpieczyć postęp.');

