const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('./engine');
function store(seed=42){const s=E.create(seed);s.cash=100000;E.buy(s,0,40);E.buy(s,1,40);E.buy(s,2,40);E.advance(s,300000);return s;}
function accept(s,items){const q=E.quoteBasket(s,items,true);for(const l of q.lines)l.returnRoll=.9;s.live.queue.push({...q,liveOffer:false,units:1,useCoupon:true,returnRoll:.9,quality:false,channel:'google'});E.advance(s,1);return s.orders.at(-1);}
test('Multiple products reserve their own actual stock and charge one parcel, payment and package',()=>{const s=store();E.basketSettings(s,'freeShippingThreshold',299);E.open(s);const o=accept(s,[{productIndex:0,qty:1},{productIndex:1,qty:1}]);assert.equal(o.lines.length,2);assert.equal(o.subtotal,328);assert.equal(o.cost,211);assert.equal(o.deliveryCharge,0);assert.equal(E.used(s),120);assert.equal(s.stock[0].qty,39);assert.equal(s.stock[1].qty,39);E.pack(s,o.id);E.ship(s);assert.equal(s.ledger.sales,328);assert.equal(s.ledger.cogs,211);assert.equal(s.ledger.shipping,13.5);assert.equal(s.ledger.packaging,2.4);assert.equal(s.ledger.fees,5.92);assert.equal(E.used(s),118);assert.ok(E.validate(s));E.close(s);const h=s.history.at(-1);assert.equal(h.aov,328);assert.equal(h.linesPerOrder,2);assert.equal(h.freeShippingRate,1);assert.equal(h.shippingSubsidy,13.5);});
test('Threshold uses discounted total; settings never reprice an accepted basket',()=>{const s=store();E.basketSettings(s,'freeShippingThreshold',299);E.settings(s,'promo','coupon');E.settings(s,'discount',10);const q=E.quoteBasket(s,[{productIndex:0,qty:1},{productIndex:1,qty:1}]);assert.equal(q.subtotal,295.2);assert.equal(q.deliveryCharge,12.99);assert.equal(q.discount,32.8);E.open(s);const o=accept(s,[{productIndex:0,qty:1},{productIndex:1,qty:1}]),saved=JSON.stringify(o);E.price(s,0,400);E.basketSettings(s,'freeShippingThreshold',199);assert.equal(JSON.stringify(o),saved);assert.ok(E.validate(s));});
test('Legacy v0.10 order migration does not alter finance, seed, discounts or historical parcel costs',()=>{const s=store();E.open(s);const o=accept(s,[{productIndex:0,qty:2}]);delete o.lines;delete o.subtotal;delete s.schemaVersion;const before=structuredClone(s);E.migrate(s);assert.equal(s.schemaVersion,2);assert.equal(s.seed,before.seed);assert.deepEqual(s.ledger,before.ledger);assert.deepEqual(s.stock,before.stock);assert.equal(s.cash,before.cash);assert.equal(s.orders[0].lines[0].priceTotal,before.orders[0].price);assert.equal(s.orders[0].lines[0].costTotal,before.orders[0].cost);assert.equal(s.orders[0].packagingCost,before.orders[0].packagingCost);assert.ok(E.validate(s));const once=JSON.stringify(s);E.migrate(s);assert.equal(JSON.stringify(s),once);});
test('Invalid line sums and duplicate products are rejected; failed reservation changes no stock',()=>{const s=store();E.open(s);const o=accept(s,[{productIndex:0,qty:1},{productIndex:1,qty:1}]);const c=structuredClone(s);c.orders[0].lines[1].productIndex=0;assert.equal(E.validate(c),false);const d=structuredClone(s);d.orders[0].lines[0].priceTotal++;assert.equal(E.validate(d),false);const q=E.quoteBasket(s,[{productIndex:0,qty:1},{productIndex:3,qty:1}]);q.lines.forEach(l=>l.returnRoll=.9);const stock=JSON.stringify(s.stock);s.live.queue.push({...q,liveOffer:false,returnRoll:.9,quality:false,channel:'google'});E.advance(s,1);assert.equal(JSON.stringify(s.stock),stock);});
test('Recommendations and a reachable free-shipping threshold increase basket attachment in matched runs',()=>{const results=[];for(const mode of ['base','recommend','threshold']){let count=0,positions=0;for(let seed=1;seed<=80;seed++){const s=store(seed);if(mode==='recommend')E.basketSettings(s,'recommendations',true);if(mode==='threshold')E.basketSettings(s,'freeShippingThreshold',199);E.open(s);E.advance(s,300000);count+=s.orders.length;positions+=s.orders.reduce((n,o)=>n+o.lines.length,0);assert.ok(s.orders.every(o=>o.lines.length<=4));}results.push(positions/count);}assert.ok(results[1]>results[0]);assert.ok(results[2]>results[0]);console.log('Mean positions: base, recommendations, threshold:',results);});
test('Multi-product CRM keeps one customer order and replenishment for every product',()=>{const s=store();E.open(s);const o=accept(s,[{productIndex:0,qty:1},{productIndex:1,qty:2}]);E.pack(s,o.id);E.ship(s);const c=s.crm.customers[o.customerId];assert.equal(c.shippedOrders,1);assert.equal(c.replenishment.length,2);assert.ok(c.replenishment.find(x=>x.productIndex===1).dueDay>c.replenishment.find(x=>x.productIndex===0).dueDay);});
