const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined});try{
const p=await b.newPage({viewport:{width:1440,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.join(__dirname,'index.html').replaceAll('\\','/'));
assert.equal(await p.locator('.product').count(),15);assert.ok(await p.evaluate(()=>game.prices.every(n=>n>=100&&n<=500)));await p.locator('[data-buy="14"]').click();await p.locator('#buy-qty').fill('5');await p.locator('#confirm-buy').click();await p.evaluate(()=>{E.advance(game,300000);render();});assert.equal(await p.evaluate(()=>game.stock[14].qty),5);
await p.locator('[data-price="14"]').fill('499');await p.locator('[data-price="14"]').press('Tab');assert.equal(await p.evaluate(()=>game.prices[14]),499);
await p.evaluate(()=>{E.buy(game,0,50);E.advance(game,300000);E.open(game);render();});await p.waitForTimeout(2200);assert.match(await p.locator('#campaign-pulse').innerText(),/Wizyty z reklam/);assert.ok(await p.evaluate(()=>game.business.channelStats.find(c=>c.id==='google').visits>0));
const before=await p.evaluate(()=>({cash:game.cash,visits:game.visits,budget:game.business.budgets.google}));await p.locator('#campaign-pulse [data-boost="google"]').click();assert.equal(await p.evaluate(()=>game.cash),before.cash-55);assert.equal(await p.evaluate(()=>game.business.budgets.google),before.budget+50);assert.ok(await p.evaluate(n=>game.visits>=n,before.visits));
await p.evaluate(()=>{E.advance(game,180000);render();});assert.ok(await p.evaluate(()=>game.orders.length>0));await p.screenshot({path:path.join(__dirname,'.test-output/premium-desktop.png')});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(__dirname,'.test-output/premium-mobile.png'),fullPage:true});
await p.evaluate(()=>save());await p.reload();assert.ok(await p.evaluate(()=>E.validate(game)));assert.equal(await p.evaluate(()=>game.prices[14]),499);
const legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/save-v0.2.json'),'utf8'));const q=await b.newPage({viewport:{width:390,height:844}});q.on('pageerror',e=>errors.push(e.message));await q.addInitScript(data=>localStorage.setItem('shopshift-save-v1',JSON.stringify(data)),legacy);await q.goto('file:///'+path.join(__dirname,'index.html').replaceAll('\\','/'));assert.ok(await q.evaluate(()=>game.stock.length===15&&E.validate(game)));assert.equal(await q.evaluate(()=>game.cash),legacy.cash);assert.equal(await q.evaluate(()=>game.orders[0].price),legacy.orders[0].price);await q.locator('#section-picker').selectOption('analytics');assert.deepEqual(errors,[]);
console.log('PASS 15 products, new SKU delivery and price, live paid visits, quick top-up billed once, queued orders, mobile layout, save/reload and legacy migration');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
