/* Command centre: presentation only. Existing economy and save format stay in engine.js. */
(function(){
document.body.classList.add('command-mode');
const icons={products:'<path d="m4 7 8-4 8 4v10l-8 4-8-4zM4 7l8 4 8-4M12 11v10M8 5l8 4"/>',orders:'<path d="M4 5h16v15H4zM8 2v6M16 2v6M8 12h8M8 16h5"/>',marketing:'<path d="m3 10 15-6v16L3 14zM6 15l2 6M21 9v6"/>',promotions:'<path d="m3 3 9 1 9 9-8 8-9-9zM7 7h.01M11 15l5-5"/>',growth:'<path d="M4 21v-9l8-6 8 6v9M2 12l10-9 10 9M9 21v-6h6v6"/>',finance:'<path d="M4 21V11h3v10M11 21V6h3v15M18 21V2h3v19"/>',analytics:'<path d="M3 3v18h18M6 15l5-5 4 3 6-8"/>'};
const icon=id=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[id]+'</svg>';
const rail=document.querySelector('.rail');rail.innerHTML='<button class="command-home" aria-label="Wróć do magazynu">S<span>↗</span></button>'+[['products','Towar'],['orders','Zamówienia'],['marketing','Marketing'],['promotions','Promocje'],['growth','Zespół'],['finance','Finanse'],['analytics','Analityka']].map(([id,label])=>'<button class="rail-btn" data-tab="'+id+'" title="'+label+'">'+icon(id)+'<span>'+label+'</span></button>').join('')+'<div class="rail-bottom"><button id="help" aria-label="Jak grać">?</button></div>';
const header=document.querySelector('header');header.insertBefore(document.querySelector('.metrics'),document.querySelector('.header-right'));header.insertBefore(document.querySelector('.day-chip'),document.querySelector('.header-right'));
const operations=document.querySelector('.operations');operations.classList.add('command-drawer');operations.setAttribute('aria-label','Zarządzanie sklepem');operations.hidden=true;
const drawerHead=document.createElement('div');drawerHead.className='drawer-heading';drawerHead.innerHTML='<div><span class="eyebrow">SHOPSHIFT / ZARZĄDZANIE</span><h2 id="drawer-title">Twój sklep</h2></div><button id="close-drawer" class="secondary" aria-label="Zamknij panel zarządzania">Wróć do magazynu ×</button>';operations.prepend(drawerHead);
const shade=document.createElement('button');shade.className='drawer-shade';shade.setAttribute('aria-label','Zamknij panel zarządzania');shade.hidden=true;operations.before(shade);
let previousFocus=null;function closeDrawer(){operations.hidden=true;shade.hidden=true;document.body.classList.remove('drawer-open');if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});}
const names={products:'Towar i ceny',orders:'Zamówienia',marketing:'Marketing',promotions:'Promocje',growth:'Zespół i rozwój',finance:'Finanse',funding:'Finansowanie',analytics:'Analityka',costs:'Koszty',customers:'Klienci',reviews:'Opinie'};
go=function(next){if(operations.hidden)previousFocus=document.activeElement;tab=next;operations.hidden=false;shade.hidden=false;document.body.classList.add('drawer-open');$('drawer-title').textContent=names[next]||'Twój sklep';render();operations.scrollTop=0;$('close-drawer').focus({preventScroll:true});};
$('close-drawer').addEventListener('click',closeDrawer);shade.addEventListener('click',closeDrawer);rail.querySelector('.command-home').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('dialog').open)closeDrawer();});
const queue=document.createElement('section');queue.id='command-orders';queue.setAttribute('aria-label','Bieżące zamówienia');queue.innerHTML='<div class="queue-heading"><h2>Bieżące zamówienia <b id="queue-number">0</b></h2><button class="text-btn" data-tab="orders">Wszystkie →</button></div><div id="order-belt"></div>';document.querySelector('.game-grid').append(queue);
const shipping=document.createElement('div');shipping.id='shipping-meter';document.querySelector('.mission-head').after(shipping);document.querySelector('.mission-head .eyebrow').textContent='WYSYŁKA';document.querySelector('.mission-head .spark').innerHTML=icon('products');
const tools=document.createElement('div');tools.className='scene-tools';tools.innerHTML='<button class="secondary" data-tab="products">▦ Regały i dostawy</button><button class="secondary" data-tab="funding">＋ Finansowanie</button><button class="secondary" data-tab="growth">⌂ Rozbudowa</button>';document.querySelector('.scene-wrap').append(tools);
const noAds=document.querySelector('#open-no-campaign')?.parentElement;if(noAds){noAds.classList.add('command-noads');$('content').before(noAds);}
const notices=document.createElement('div');notices.id='command-alerts';document.querySelector('main').append(notices);for(const id of ['stock-alerts','credit-status','funding-suggestion'])if($(id))notices.append($(id));
const shortcut=document.createElement('button');shortcut.className='goal-open';shortcut.textContent='Cel i rozwój →';shortcut.dataset.tab='growth';$('active-goal')?.append(shortcut);
let queueHTML='',meterHTML='';const refresh=window.refreshLiveUI;window.refreshLiveUI=function(){refresh?.();document.body.dataset.phase=game.phase;const pending=game.orders.filter(o=>['new','packed'].includes(o.status)),packed=pending.filter(o=>o.status==='packed').length,waiting=pending.length-packed;
$('queue-number').textContent=pending.length;
const html=pending.length?pending.slice(0,24).map(o=>{const lines=E.orderLines(o),p=E.PRODUCTS[lines[0].productIndex];return '<button class="order-tile '+o.status+'" '+(o.status==='new'&&game.phase==='fulfill'&&E.packingLeft(game)?'data-pack="'+o.id+'"':'data-tab="orders"')+' title="'+escapeHTML(basketLabel(o))+'"><span class="order-id">#'+o.id+' <i>'+E.qty(o)+' szt.</i></span><div class="tile-art">'+art(p)+'</div><strong>'+escapeHTML(p.name)+(lines.length>1?' +'+(lines.length-1):'')+'</strong><small>'+money(o.price)+'</small><span class="order-state">'+(o.status==='packed'?'✓ Spakowane':'▣ Do spakowania')+'</span></button>';}).join('')+(pending.length>24?'<button class="order-tile more-orders" data-tab="orders">+'+(pending.length-24)+'<small>Zobacz pozostałe</small></button>':''):'<div class="queue-empty"><span>▣</span><div><strong>'+(game.phase==='plan'?'Przygotuj sklep na klientów':'Czekamy na kolejne zamówienie')+'</strong><p>'+(game.phase==='plan'?'Zamów towar, wybierz marketing i otwórz dzień.':'Ruch, ceny i dostępność produktów decydują o zakupach.')+'</p></div><button class="secondary" data-tab="marketing">Marketing →</button></div>';
if(html!==queueHTML){$('order-belt').innerHTML=html;queueHTML=html;}
const m='<div class="parcel-total"><strong>'+packed+'<em> / 10</em></strong><span>Spakowane paczki</span></div><div class="parcel-slots" aria-hidden="true">'+Array.from({length:10},(_,i)=>'<i class="'+(i<packed?'filled':'')+'">▣</i>').join('')+'</div>';if(m!==meterHTML){shipping.innerHTML=m;meterHTML=m;}
$('drawer-title').textContent=names[tab]||'Twój sklep';$('scene-pack').title=waiting?'Kliknij, aby spakować jedno zamówienie':'Brak zamówień do spakowania';
};window.refreshLiveUI();
})();

const goalLink=document.getElementById('active-goal');if(goalLink){goalLink.tabIndex=0;goalLink.setAttribute('role','button');goalLink.setAttribute('aria-label','Otwórz cel i rozwój firmy');goalLink.addEventListener('click',e=>{if(!e.target.closest('button'))go('growth');});goalLink.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go('growth');}});}
