const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('./engine.js');
const drain=s=>{for(let n=0;n<200&&(s.live?.queue.length||s.orders.some(o=>o.status==='new'));n++)E.advance(s,30000);};
const finish=s=>{drain(s);if(s.orders.some(o=>o.status==='packed'))E.ship(s);E.close(s);};
const stocked=()=>{const s=E.create();E.buy(s,0,100);E.advance(s,300000);return s;};
const budgets=(s,n)=>E.CHANNELS.forEach(c=>E.settings(s,'budget:'+c.id,c.id==='google'?n:0));
function balance(s){const assets=s.stock.reduce((a,b)=>a+b.value,0)+s.deliveries.reduce((a,b)=>a+b.value,0)+s.orders.filter(o=>['new','packed'].includes(o.status)).reduce((a,b)=>a+b.cost,0);assert.ok(Math.abs(s.cash-(10000+E.profit(s.total)-assets))<.06,JSON.stringify({cash:s.cash,assets,p:E.profit(s.total)}));assert.ok(s.stock.every(x=>x.qty>=0&&x.value>=0));assert.ok(E.used(s)<=E.LEVELS[s.level].capacity);assert.ok(E.validate(s));}
test('Purchase is an asset; minimum, capacity, funds and numeric bounds enforced',()=>{const s=stocked();assert.equal(s.cash,7600);assert.equal(E.profit(s.total),0);for(const args of [[0,2],[0,151],[0,NaN],[0,2.5],[6,5],[0,10,1]])assert.throws(()=>E.buy(s,...args));balance(s);});
test('Agency: 1500/30 fixed plus exactly 10% of configured daily spend',()=>{const s=stocked();budgets(s,100);E.open(s);assert.equal(s.ledger.ads,100);assert.equal(s.ledger.agency,10);assert.throws(()=>E.open(s));E.close(s);assert.equal(s.ledger.agency,60);assert.equal(s.ledger.software,3.3);balance(s);});
test('Fixed agency cost persists with no ads or orders; self management removes it',()=>{for(const agency of [false,true]){const s=stocked();budgets(s,0);E.settings(s,'agency',agency);E.open(s);E.close(s);assert.equal(s.ledger.agency,agency?50:0);balance(s);}});
test('Paid channels have independent spend, traffic and attribution',()=>{const s=stocked();for(const c of E.CHANNELS)E.settings(s,'budget:'+c.id,c.id==='articles'?350:100);E.open(s);assert.equal(s.ledger.ads,750);assert.equal(s.business.channelStats.length,6);assert.ok(s.business.channelStats.filter(c=>c.id!=='organic').every(c=>c.visits>0));drain(s);if(s.orders.some(o=>o.status==='packed'))E.ship(s);assert.equal(E.round(s.business.channelStats.reduce((a,c)=>a+c.sales,0)),s.ledger.sales);balance(s);});
test('New stores have only 2–5 organic visits and rarely sell without marketing',()=>{let total=0;for(let seed=1;seed<=150;seed++){const s=E.create(seed);E.buy(s,0,20);budgets(s,0);E.settings(s,'agency',false);E.open(s);assert.ok(s.visits>=2&&s.visits<=5);total+=s.live.queue.length;}assert.ok(total<30);});
test('SEO has a lag and does not buy immediate organic ranking',()=>{const a=stocked(),b=structuredClone(a);budgets(a,0);budgets(b,0);a.business.seoPoints=10000;b.business.seoPoints=10000;a.business.seoAge=29;b.business.seoAge=30;E.open(a);E.open(b);assert.ok(a.visits<=5);assert.ok(b.visits>a.visits+100);});
test('Arrival spacing remains variable 10–50 sec; no stock reserved before arrival',()=>{const s=stocked();budgets(s,800);E.open(s);assert.equal(s.stock[0].qty,100);assert.equal(s.orders.length,0);const delays=[];while(s.live.queue.length){const d=s.live.nextIn;delays.push(d);assert.ok(d>=10000&&d<=50000);const before=s.orders.length;E.advance(s,d-1);assert.equal(s.orders.length,before);assert.equal(E.advance(s,1).filter(x=>x.type==='order').length,1);}assert.ok(new Set(delays).size>1);balance(s);});
test('Automatic pack only after 16 sec; worker uses 9 sec',()=>{for(const worker of [false,true]){const s=stocked();s.worker=worker;s.level=worker?1:0;E.open(s);E.advance(s,s.live.nextIn);const duration=E.packingDuration(s);E.advance(s,duration-1);assert.equal(s.orders[0].status,'new');E.advance(s,1);assert.equal(s.orders[0].status,'packed');balance(s);}});
test('Manual assistance cannot double-pack',()=>{const s=stocked();E.open(s);E.advance(s,s.live.nextIn+3000);E.pack(s,s.orders[0].id);E.advance(s,13000);assert.equal(s.packedToday,1);assert.throws(()=>E.pack(s,s.orders[0].id));});
test('3+1 charges three units and reserves/costs all four',()=>{const s=stocked();E.settings(s,'promo','bundle');const quote=E.offer(s,0);assert.equal(quote.qty,4);assert.equal(quote.price,177);assert.equal(quote.discount,59);assert.equal(E.unitEconomics(s,0).cost,96);E.open(s);E.advance(s,s.live.nextIn);assert.equal(s.stock[0].qty,96);assert.equal(s.orders[0].cost,96);assert.equal(E.used(s),100);balance(s);});
test('No bundle can be sold with fewer than four units',()=>{const s=E.create();s.stock[0]={qty:3,value:72};s.cash-=72;E.settings(s,'promo','bundle');budgets(s,1500);E.open(s);assert.equal(s.live.queue.length,0);assert.ok(s.lost>0);balance(s);});
test('Sale and coupon discounts are snapshot revenue reductions, never double-costed',()=>{const s=stocked();E.settings(s,'discount',20);E.settings(s,'promo','sale');assert.equal(E.offer(s,0,2).price,94.4);E.settings(s,'promo','coupon');assert.equal(E.offer(s,0,2,false).price,118);assert.equal(E.offer(s,0,2,true).price,94.4);E.open(s);E.settings(s,'discount',50);drain(s);const expected=E.round(s.orders.reduce((a,o)=>a+o.price+o.deliveryCharge,0));E.ship(s);assert.equal(s.ledger.sales,expected);balance(s);});
test('Courier, packaging and payment fees booked separately; settings frozen in order',()=>{const s=stocked();E.open(s);drain(s);const expected={sales:0,shipping:0,packaging:0,fees:0,cost:0};for(const o of s.orders){expected.sales+=o.price+o.deliveryCharge;expected.shipping+=o.shippingCost;expected.packaging+=o.packagingCost;expected.fees+=E.round((o.price+o.deliveryCharge)*o.paymentRate+o.paymentFixed);expected.cost+=o.cost;}E.ship(s);for(const k of ['sales','shipping','packaging','fees'])assert.equal(s.ledger[k],E.round(expected[k]));assert.equal(s.ledger.cogs,E.round(expected.cost));assert.throws(()=>E.ship(s));balance(s);});
test('Employee payroll includes employer cost once per calendar day',()=>{const s=stocked();s.level=1;E.hire(s);E.open(s);E.close(s);assert.equal(s.ledger.payroll,220.88);assert.equal(s.ledger.fixed,85);balance(s);});
test('Early close cancels accepted multi-unit orders and drops future demand without fees',()=>{const s=stocked();E.settings(s,'promo','bundle');E.open(s);E.advance(s,s.live.nextIn+2000);E.close(s);assert.equal(s.stock[0].qty,100);assert.equal(E.used(s),100);assert.equal(s.ledger.sales,0);assert.ok(s.rating<4.6);assert.equal(s.live.queue.length,0);balance(s);});
test('Returns refund discounted basket plus paid delivery and do not restore opened cosmetics',()=>{const s=stocked();E.settings(s,'promo','bundle');E.open(s);s.live.queue.forEach(o=>o.returnRoll=0);finish(s);const revenue=s.ledger.sales,n=s.shipped,stock=s.stock[0].qty;E.next(s);budgets(s,0);E.open(s);E.close(s);E.next(s);assert.equal(s.ledger.refunds,revenue);assert.equal(s.ledger.returnFees,n*6);assert.equal(s.stock[0].qty,stock);balance(s);});
test('Old saves migrate with historical finances and accepted order prices intact',()=>{const s=JSON.parse(JSON.stringify(require('./fixtures/save-v0.2.json')));assert.ok(E.validate(s));const cash=s.cash,cost=s.orders[0].cost;E.migrate(s);assert.equal(s.cash,cash);assert.equal(s.ledger.agency,0);E.advance(s,11000);assert.equal(s.orders[0].status,'packed');E.ship(s);assert.equal(s.ledger.sales,68);assert.equal(s.ledger.cogs,cost);assert.equal(s.ledger.shipping,11);assert.equal(s.ledger.packaging,0);balance(s);});
test('Save roundtrip preserves all promotions, new cost snapshots and timers',()=>{const s=stocked();E.settings(s,'promo','bundle');E.open(s);E.advance(s,s.live.nextIn+5000);const copy=JSON.parse(JSON.stringify(s));assert.ok(E.validate(copy));assert.deepEqual(E.advance(s,30000),E.advance(copy,30000));assert.deepEqual(s,copy);balance(s);});
test('Reject malformed settings, quantities, snapshots and nested saves',()=>{const s=stocked();for(const [field,value] of [['budget:meta',NaN],['budget:articles',100],['rate:salaryGross',4000],['discount',70],['promo','evil']])assert.throws(()=>E.settings(s,field,value));E.open(s);for(const change of [x=>x.business.budgets.google=Infinity,x=>x.business.promo.type='unknown',x=>x.live.nextIn=-1,x=>x.live.queue[0].qty=99,x=>x.live.queue[0].packagingCost=-1]){const x=structuredClone(s);change(x);assert.equal(E.validate(x),false);}assert.throws(()=>E.advance(s,-1));});
test('30 days: cash/profit/assets reconcile through costs, promotions and reinvestment',()=>{const s=E.create();E.settings(s,'promo','bundle');for(let day=0;day<30;day++){if(s.cash<500){budgets(s,0);E.settings(s,'agency',false);}for(let i=0;i<6;i++)if(s.stock[i].qty<8&&E.used(s)+12<=E.LEVELS[s.level].capacity&&s.cash>E.PRODUCTS[i].cost*12+600)E.buy(s,i,12);E.open(s);while(s.live.queue.length||s.orders.some(o=>o.status==='new')){E.advance(s,30000);balance(s);}finish(s);balance(s);E.next(s);balance(s);}assert.ok(Number.isFinite(s.cash));console.log('30-day revised scenario:',s.cash,'cash,',s.shipped,'shipments');});
test('SEO spend matures 30 days after each investment, including established stores',()=>{const s=stocked();budgets(s,0);E.settings(s,'agency',false);s.day=45;s.business.seoAge=44;E.settings(s,'seoBudget',100);E.open(s);E.close(s);assert.equal(s.business.seoPoints,0);E.next(s);E.settings(s,'seoBudget',0);for(let d=46;d<75;d++){assert.equal(s.business.seoPoints,0);E.open(s);E.close(s);E.next(s);}assert.equal(s.day,75);assert.equal(s.business.seoPoints,100);assert.equal(s.business.seoPending.length,0);balance(s);});

test('Deliveries run in every phase, retain value and never arrive early',()=>{for(const phase of ['plan','fulfill','report']){const s=E.create(47);s.phase=phase;const cash=s.cash;E.buy(s,1,20,1);const d=s.deliveries[0];assert.ok(d.remainingMs>=60000&&d.remainingMs<=300000);assert.equal(s.stock[1].qty,0);assert.equal(s.cash,cash-d.value);assert.equal(E.used(s),20);E.advance(s,d.remainingMs-1);assert.equal(s.stock[1].qty,0);assert.equal(E.advance(s,1)[0].type,'delivery');assert.equal(s.stock[1].qty,20);assert.equal(s.deliveries.length,0);balance(s);}});
test('Pending deliveries survive day rollover, migration and save/reload',()=>{const s=E.create();E.buy(s,0,10);const eta=s.deliveries[0].remainingMs;E.open(s);E.close(s);E.next(s);assert.equal(s.deliveries[0].remainingMs,eta);const copy=JSON.parse(JSON.stringify(s));assert.ok(E.validate(copy));E.migrate(copy);assert.equal(copy.deliveries[0].remainingMs,eta);E.advance(copy,eta);assert.equal(copy.stock[0].qty,10);balance(copy);const legacy=E.create();legacy.deliveries=[{index:0,qty:10,value:240,due:2}];legacy.cash-=240;assert.ok(E.validate(legacy));E.migrate(legacy);assert.ok(legacy.deliveries[0].remainingMs>=60000);balance(legacy);});
test('New prices and promotions affect upcoming orders, never accepted orders',()=>{const s=stocked();budgets(s,800);E.open(s);E.advance(s,s.live.nextIn);const old=structuredClone(s.orders[0]);E.price(s,0,70);E.settings(s,'promo','bundle');E.advance(s,s.live.nextIn);const next=s.orders[1];assert.equal(next.price,210);assert.equal(next.qty,4);assert.equal(s.orders[0].price,old.price);assert.equal(s.orders[0].qty,old.qty);E.buy(s,1,5);assert.equal(s.deliveries.length,1);balance(s);});

test('A 0.3 waiting customer uses edited prices after migration',()=>{const s=stocked();E.open(s);for(const o of s.live.queue){delete o.liveOffer;delete o.units;delete o.useCoupon;}E.migrate(s);E.price(s,0,80);E.settings(s,'promo','bundle');E.advance(s,s.live.nextIn);assert.equal(s.orders[0].price,240);balance(s);});
