/* SHOPSHIFT — deterministic simulation, independent of DOM and platform. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.Shopshift=api;})(globalThis,function(){
'use strict';
const PRODUCTS=[
{id:'serum',name:'Dewdrop',kind:'Serum nawilżające',cost:112,price:179,color:'#c65969',shape:'dropper'},
{id:'cream',name:'Cloud Nine',kind:'Krem do twarzy',cost:99,price:149,color:'#c1c1c1',shape:'jar'},
{id:'cleanser',name:'Fresh Start',kind:'Żel oczyszczający',cost:75,price:109,color:'#bababa',shape:'pump'},
{id:'mist',name:'Soft Rain',kind:'Mgiełka do twarzy',cost:71,price:100,color:'#b3b3b3',shape:'spray'},
{id:'mask',name:'Sunday Reset',kind:'Maska regenerująca',cost:146,price:219,color:'#de939d',shape:'jar'},
{id:'oil',name:'Golden Hour',kind:'Olejek do twarzy',cost:180,price:279,color:'#c4c4c4',shape:'dropper'},
{id:'night',name:'Midnight Repair',kind:'Krem nocny z ceramidami',cost:215,price:329,color:'#9c8aac',shape:'jar'},
{id:'eyes',name:'Bright Eyes',kind:'Serum pod oczy',cost:163,price:249,color:'#d2b8a5',shape:'dropper'},
{id:'spf',name:'City Shield',kind:'Krem ochronny SPF 50',cost:119,price:169,color:'#dad4c8',shape:'pump'},
{id:'peel',name:'Velvet Peel',kind:'Peeling enzymatyczny',cost:130,price:199,color:'#c78b98',shape:'jar'},
{id:'retinal',name:'After Dark',kind:'Serum z retinalem',cost:245,price:379,color:'#8c829b',shape:'dropper'},
{id:'body',name:'Body Ritual',kind:'Balsam do ciała',cost:153,price:229,color:'#bbaaa0',shape:'pump'},
{id:'hair',name:'Silk Therapy',kind:'Olejek do włosów',cost:168,price:259,color:'#b6a77c',shape:'dropper'},
{id:'elixir',name:'Lumière Elixir',kind:'Koncentrat peptydowy',cost:285,price:449,color:'#a99c85',shape:'dropper'},
{id:'signature',name:'Signature 500',kind:'Krem luksusowy',cost:313,price:500,color:'#777782',shape:'jar'}];
const LEVELS=[{name:'Domowe studio',size:'24 m²',capacity:150,rent:35,limit:25,upgrade:0},{name:'Pracownia marki',size:'70 m²',capacity:450,rent:85,limit:65,upgrade:2400},{name:'Centrum wysyłek',size:'180 m²',capacity:1200,rent:170,limit:160,upgrade:6000}];
const CAMPAIGNS=[{name:'Ruch organiczny',cost:0,visits:24},{name:'Social starter',cost:60,visits:95},{name:'Beauty creators',cost:180,visits:220},{name:'Pełna kampania',cost:480,visits:430}];

// Market references and editable scenario assumptions are documented in REALIA.md.
const CHANNELS=[
{id:'google',name:'Google Ads',cpc:1.2,cvr:.075,description:'Wyszukiwanie: większa intencja zakupu.'},
{id:'meta',name:'Meta Ads · Facebook',cpc:.8,cvr:.045,description:'Szerokie dotarcie, niższa intencja zakupu.'},
{id:'instagram',name:'Instagram',cpc:.9,cvr:.04,description:'Osobna pula reklam wizualnych; część ekosystemu Meta.'},
{id:'tiktok',name:'TikTok',cpc:.55,cvr:.03,description:'Tańszy ruch, duża zmienność i niższa konwersja.'},
{id:'articles',name:'Artykuły zewnętrzne',cpc:0,cvr:.045,description:'350 zł za publikację; ruch polecający i wolny rozwój marki.'}];
const EXTRA_COSTS=['agency','packaging','payroll','software','interest','loanFees','tax'];
function defaults(){return {budgets:{google:150,meta:0,instagram:0,tiktok:0,articles:0},agency:true,seoBudget:0,seoPoints:0,seoPending:[],seoAge:0,brand:0,promo:{type:'none',percent:10},rates:{agencyMonthly:1500,agencyPercent:10,parcel:13.5,packaging:1.8,customerDelivery:12.99,salaryGross:5500,employerPercent:20.48,softwareMonthly:299,returnHandling:6,paymentPercent:1.5,paymentFixed:1}};}
function migrate(s){if(!s.pacingRevision){if(s.live)s.live.nextIn=Math.min(s.live.nextIn,15000);s.pacingRevision=1;}if(s.dayElapsed===undefined)s.dayElapsed=0;if(!s.tax)s.tax={loss:0};
if(s.catalogRevision!==2){for(let i=0;i<PRODUCTS.length;i++){if(!s.stock[i])s.stock.push({qty:0,value:0});if(s.prices[i]===undefined||s.prices[i]<100)s.prices[i]=PRODUCTS[i].price;}
if(s.stockWatch)while(s.stockWatch.length<PRODUCTS.length)s.stockWatch.push(false);
if(s.traffic){while(s.traffic.products.length<PRODUCTS.length)s.traffic.products.push({views:0,carts:0});for(const source of s.traffic.sources){const channel=CHANNELS.find(c=>c.id===source.id);if(channel)source.cvr=channel.cvr;}}
s.catalogRevision=2;log(s,'Nowa kolekcja: 15 produktów, ceny 100–500 zł. Zachowano koszt wcześniejszych zapasów i przyjęte zamówienia.');}
if(!s.stockWatch)s.stockWatch=PRODUCTS.map((_,i)=>s.stock[i].qty>0||s.deliveries.some(d=>d.index===i)||s.orders.some(o=>o.index===i)||s.returns.some(o=>o.index===i));if(!s.credit)s.credit={loan:null,borrowed:0,repaid:0};for(const o of s.live?.queue||[]){if(o.qty!==undefined&&o.liveOffer===undefined){o.liveOffer=true;o.units=Math.min(3,o.qty);o.useCoupon=o.promo==='coupon'?o.discount>0:true;}}for(const d of s.deliveries){if(d.remainingMs===undefined){d.remainingMs=60000+Math.floor(rng(s)*240001);delete d.due;}} if(!s.business){s.business=defaults();s.business.budgets.google=CAMPAIGNS[s.campaign]?.cost||0;}if(!s.business.seoPending)s.business.seoPending=[];for(const l of [s.ledger,s.total,...s.history])for(const k of EXTRA_COSTS)if(l[k]===undefined)l[k]=0;return s;}
function config(s){return s.business||defaults();}
function qty(o){return o.qty||1;}
function spend(s){const b=config(s);return round(Object.values(b.budgets).reduce((a,n)=>a+n,0)+b.seoBudget);}
function dayCosts(s){const b=config(s),r=b.rates;return {ads:spend(s),agencyVariable:b.agency?round(spend(s)*r.agencyPercent/100):0,agencyFixed:b.agency?round(r.agencyMonthly/30):0,payroll:s.worker?round(r.salaryGross*(1+r.employerPercent/100)/30):0,software:round(r.softwareMonthly/30),rent:LEVELS[s.level].rent};}
function settings(s,field,value){if(s.phase!=='plan'&&!['promo','discount'].includes(field))throw Error('Plan zmienisz przed kolejnym dniem.');migrate(s);const b=s.business;
if(field.startsWith('budget:')){const id=field.slice(7);if(!CHANNELS.some(c=>c.id===id)||!Number.isFinite(value)||value<0||value>3000||(id==='articles'&&value%350!==0))throw Error('Budżet: 0–3000 zł. Publikacje po 350 zł/szt.');b.budgets[id]=round(value);}
else if(field==='agency'){if(typeof value!=='boolean')throw Error('Nieprawidłowa obsługa kampanii.');b.agency=value;}
else if(field==='seoBudget'){if(!Number.isFinite(value)||value<0||value>500)throw Error('Budżet SEO: 0–500 zł/dzień.');b.seoBudget=round(value);}
else if(field==='promo'){if(!['none','sale','coupon','bundle'].includes(value))throw Error('Nieprawidłowa promocja.');b.promo.type=value;}
else if(field==='discount'){if(!Number.isFinite(value)||value<1||value>50)throw Error('Rabat: 1–50%.');b.promo.percent=round(value);}
else if(field.startsWith('rate:')){const id=field.slice(5),limits={agencyMonthly:[0,10000],agencyPercent:[0,30],parcel:[5,50],packaging:[.5,15],customerDelivery:[0,30],salaryGross:[4806,20000],employerPercent:[0,40],softwareMonthly:[0,3000],returnHandling:[0,50],paymentPercent:[0,5],paymentFixed:[0,5]};if(!limits[id]||!Number.isFinite(value)||value<limits[id][0]||value>limits[id][1])throw Error('Wartość poza zakresem dla tego kosztu.');b.rates[id]=round(value);}
else throw Error('Nieznane ustawienie.');}
function offer(s,index,units=1,useCoupon=true){const b=config(s),p=b.promo;let quantity=p.type==='bundle'?4:units;const base=round(s.prices[index]*quantity),discount=p.type==='bundle'?s.prices[index]:((p.type==='sale'||p.type==='coupon'&&useCoupon)?round(base*p.percent/100):0);const price=round(base-discount),deliveryCharge=s.freeShipping?0:b.rates.customerDelivery;return {qty:quantity,basePrice:base,discount,price,promo:p.type,deliveryCharge,shippingCost:b.rates.parcel,packagingCost:round(b.rates.packaging+(quantity>2?.6:0)),paymentRate:b.rates.paymentPercent/100,paymentFixed:b.rates.paymentFixed,returnHandling:b.rates.returnHandling};}
function purchaseEconomics(s,index,units=1,supplier=0){const o=unitEconomics(s,index,units),unitCost=round(PRODUCTS[index].cost*(supplier===1?.86:1)),cost=round(unitCost*o.qty);return {...o,cost,unitCost,contribution:round(o.contribution+o.cost-cost)};}
function unitEconomics(s,index,units=1){const o=offer(s,index,units),st=s.stock[index],cost=round((st.qty?st.value/st.qty:PRODUCTS[index].cost)*o.qty),fee=round((o.price+o.deliveryCharge)*o.paymentRate+o.paymentFixed);return {...o,cost,fee,contribution:round(o.price+o.deliveryCharge-cost-o.shippingCost-o.packagingCost-fee)};}

const empty=()=>({sales:0,cogs:0,shipping:0,fees:0,ads:0,fixed:0,refunds:0,returnFees:0,setup:0,agency:0,packaging:0,payroll:0,software:0,interest:0,loanFees:0,tax:0});
const profit=l=>l.sales-l.cogs-l.shipping-l.fees-l.ads-l.fixed-l.refunds-l.returnFees-l.setup-(l.agency||0)-(l.packaging||0)-(l.payroll||0)-(l.software||0)-(l.interest||0)-(l.loanFees||0)-(l.tax||0);
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
function create(seed=18371){return {version:1,pacingRevision:1,dayElapsed:0,tax:{loss:0},catalogRevision:2,stockWatch:PRODUCTS.map(()=>false),credit:{loan:null,borrowed:0,repaid:0},business:defaults(),seed,day:1,phase:'plan',cash:10000,level:0,rating:4.6,ratingCount:5,stock:PRODUCTS.map(()=>({qty:0,value:0})),prices:PRODUCTS.map(p=>p.price),deliveries:[],orders:[],returns:[],reviews:[],history:[],ledger:empty(),total:empty(),campaign:1,freeShipping:false,worker:false,shipped:0,packedToday:0,visits:0,lost:0,nextId:1001,tutorial:0,log:['Witaj w swoim pierwszym sklepie. Kup towar, ustaw ceny i otwórz dzień.']};}
function rng(s){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
function log(s,msg){s.log.unshift(msg);s.log=s.log.slice(0,12);}
function entry(s,key,n){n=round(n);s.ledger[key]=round((s.ledger[key]||0)+n);s.total[key]=round((s.total[key]||0)+n);}
function used(s){return s.stock.reduce((a,b)=>a+b.qty,0)+s.deliveries.reduce((a,b)=>a+b.qty,0)+s.orders.filter(o=>o.status==='new'||o.status==='packed').reduce((n,o)=>n+qty(o),0);}
function buy(s,index,qty,supplier=0){

if(!Number.isInteger(index)||!PRODUCTS[index]||!Number.isInteger(qty)||qty<1||qty>500||![0,1].includes(supplier))throw Error('Nieprawidłowa dostawa.');
const unit=round(PRODUCTS[index].cost*(supplier===1?.86:1));const cost=round(unit*qty);
if(qty<(supplier===1?20:5))throw Error('Minimum dostawcy: '+(supplier===1?20:5)+' sztuk.');
if(used(s)+qty>LEVELS[s.level].capacity)throw Error('Brak miejsca w magazynie. Zmniejsz dostawę lub rozbuduj firmę.');
if(cost>s.cash)throw Error('Brakuje gotówki na tę dostawę.');
migrate(s);s.stockWatch[index]=true;s.cash=round(s.cash-cost);
s.deliveries.push({index,qty,value:cost,remainingMs:60000+Math.floor(rng(s)*240001)});
s.tutorial=Math.max(s.tutorial,1);log(s,'Zakup: '+qty+' × '+PRODUCTS[index].name+' za '+cost+' zł'+' · dostawa za 1–5 minut.');return cost;
}
function price(s,index,value){if(!PRODUCTS[index]||!Number.isFinite(value)||value<100||value>500)throw Error('Cena musi wynosić 100–500 zł.');s.prices[index]=round(value);s.tutorial=Math.max(s.tutorial,2);}
function review(s,stars,text){s.rating=(s.rating*s.ratingCount+stars)/(s.ratingCount+1);s.ratingCount++;s.reviews.unshift({day:s.day,stars,text});s.reviews=s.reviews.slice(0,25);}
// Plan demand once; accept each order only when its arrival timer expires.
function open(s){
if(s.phase!=='plan')throw Error('Dzień jest już otwarty.');migrate(s);const b=s.business,costs=dayCosts(s),upfront=round(costs.ads+costs.agencyVariable);
if(upfront>0&&s.cash<upfront)throw Error('Brak gotówki na reklamę i prowizję agencji. Zmniejsz budżety.');
s.cash=round(s.cash-upfront);entry(s,'ads',costs.ads);entry(s,'agency',costs.agencyVariable);b.dayCosts=costs;s.phase='fulfill';s.dayElapsed=0;s.orders=[];s.lost=0;s.packedToday=0;s.visits=0;
b.channelStats=[];
const growth=organicGrowth(s),organic=Math.round(2+rng(s)*3+growth.extra);
s.traffic={elapsed:0,duration:300000,nextIn:1000,sources:[],products:PRODUCTS.map(()=>({views:0,carts:0})),minutes:[]};
addSource(s,'organic',0,organic,growth.cvr,1,1);
for(const c of CHANNELS){const budget=b.budgets[c.id];if(!budget)continue;const variation=.7+rng(s)*.6,overlap=c.id==='instagram'&&b.budgets.meta>0?.85:1;addSource(s,c.id,budget,Math.round(reach(c.id,budget)*variation*overlap),c.cvr,variation,overlap);}
s.live={queue:[],nextIn:0,job:null};s.tutorial=Math.max(s.tutorial,3);
log(s,'Sklep otwarty. Ruch napływa przez 5 minut aktywnej gry; ceny i promocje wpływają na kolejnych odwiedzających.');
}
const KNEES={google:300,meta:250,instagram:180,tiktok:150,articles:700};
function reach(id,budget){const c=CHANNELS.find(c=>c.id===id);if(!c)return 0;const k=KNEES[id],effective=budget<=k?budget:k*(1+Math.log(budget/k));return effective/(c.cpc||350/27.5);}
function audience(id,budget){return 1/(1+Math.max(0,budget/(KNEES[id]||300)-1)*.18);}
function conversion(s,index,base,quality=1){const b=config(s),promo=b.promo,discount=promo.type==='sale'?promo.percent/100:promo.type==='coupon'?promo.percent/100*.65:promo.type==='bundle'?.25:0;
const relative=s.prices[index]*(1-discount)/PRODUCTS[index].price,trust=Math.max(.45,Math.min(1.3,s.rating/4.5))*(1+Math.min(.3,b.brand*.002));
return Math.min(.18,base*quality*trust*Math.pow(1/relative,1.7)*(promo.type==='bundle'?1.08:1)*(s.freeShipping?1.08:1));}
function addSource(s,id,budget,planned,cvr,variation,overlap){const t=s.traffic,name=CHANNELS.find(c=>c.id===id)?.name||'Organiczne / marka';t.sources.push({id,planned,served:0,start:t.elapsed,cvr,variation,overlap});s.business.channelStats.push({id,name,spend:budget,visits:0,plannedVisits:planned,views:0,carts:0,checkouts:0,accepted:0,orderedValue:0,orders:0,sales:0,contribution:0,lost:0});}
function hasDemand(s){return s.phase==='fulfill'&&!!(s.live?.queue.length||s.traffic&&s.traffic.elapsed<s.traffic.duration);}
function boost(s,id,amount){if(s.phase!=='fulfill'||!s.traffic||s.traffic.elapsed>=s.traffic.duration)throw Error('Doładuj kampanię podczas trwania ruchu.');const c=CHANNELS.find(x=>x.id===id),b=s.business;if(!c||!Number.isFinite(amount)||amount<=0||b.budgets[id]+amount>3000||(id==='articles'&&amount%350!==0))throw Error('Nieprawidłowe doładowanie; limit 3000 zł na kanał.');const fee=b.agency?round(amount*b.rates.agencyPercent/100):0;if(s.cash<amount+fee)throw Error('Brak środków na doładowanie i agencję.');let source=s.traffic.sources.find(x=>x.id===id);const old=b.budgets[id];if(!source){addSource(s,id,0,0,c.cvr,.7+rng(s)*.6,id==='instagram'&&b.budgets.meta>0?.85:1);source=s.traffic.sources.find(x=>x.id===id);}const extra=Math.max(0,Math.round((reach(id,old+amount)-reach(id,old))*source.variation*source.overlap));const stats=b.channelStats.find(x=>x.id===id);source.planned=source.planned-source.served+extra;source.served=0;source.start=s.traffic.elapsed;stats.plannedVisits+=extra;stats.spend=round(stats.spend+amount);b.budgets[id]=round(old+amount);s.cash=round(s.cash-amount-fee);entry(s,'ads',amount);entry(s,'agency',fee);b.dayCosts.ads+=amount;b.dayCosts.agencyVariable+=fee;log(s,'Doładowano '+c.name+': '+amount+' zł + '+fee+' zł agencji.');}
function trafficTick(s){const t=s.traffic,b=s.business,live=ensureLive(s);t.elapsed=Math.min(t.duration,t.elapsed+1000);const minute=Math.min(Math.ceil(t.duration/60000)-1,Math.floor((t.elapsed-1)/60000));if(!t.minutes[minute])t.minutes[minute]={visits:0,orders:0};
for(const source of t.sources){const stats=b.channelStats.find(c=>c.id===source.id),target=Math.floor(source.planned*Math.pow((t.elapsed-source.start)/(t.duration-source.start),.65));
while(source.served<target){source.served++;stats.visits++;s.visits++;t.minutes[minute].visits++;const available=PRODUCTS.map((_,i)=>i).filter(i=>s.stock[i].qty>0||s.deliveries.some(d=>d.index===i));
// Every session samples the current offer; five independent draws keep scenarios comparable.
const pick=rng(s),roll=rng(s),basket=rng(s),coupon=rng(s),returnRoll=rng(s);if(!available.length)continue;const index=available[Math.floor(pick*available.length)],cvr=conversion(s,index,source.cvr,audience(source.id,stats.spend));
if(roll<.85){stats.views++;t.products[index].views++;}if(roll<Math.min(.7,cvr*4)){stats.carts++;t.products[index].carts++;}if(roll<Math.min(.5,cvr*2))stats.checkouts++;
if(roll>=cvr)continue;const units=basket<.55?1:basket<.865?2:3,o=offer(s,index,units,coupon<.65);
const reserved=live.queue.filter(x=>x.index===index).reduce((n,x)=>n+qty(x),0);if(s.stock[index].qty-reserved<o.qty||s.orders.length+live.queue.length>=LEVELS[s.level].limit){stats.lost++;s.lost++;continue;}
if(!live.queue.length)live.nextIn=delay(s);live.queue.push({...o,liveOffer:true,units,useCoupon:coupon<.65,index,channel:source.id,freeShipping:s.freeShipping,returnRoll,quality:s.prices[index]/PRODUCTS[index].price>1.3});
}}
t.nextIn=t.elapsed<t.duration?1000:0;
}

function organicGrowth(s){const b=config(s),reputation=Math.max(.4,Math.min(1.1,s.rating/4.6)),age=Math.min(240,Math.max(0,s.day-1)*6),returning=Math.min(180,s.shipped*.8),brand=Math.min(100,b.brand*.4),seo=b.seoAge>=30?Math.min(250,b.seoPoints*.025):0;return {age,returning,brand,seo,extra:(age+returning+brand)*reputation+seo,cvr:.012+Math.min(.023,s.shipped*.0003)};}
function delay(s){return 5000+Math.floor(rng(s)*10001);}
function ensureLive(s){if(!s.live)s.live={queue:[],nextIn:0,job:null};return s.live;}
function packingDuration(s){return s.worker?9000:16000;}
const DAY_DURATION=300000;
function tick(s,ms){if(!Number.isFinite(ms)||ms<0||ms>3600000)throw Error('Nieprawidłowy krok czasu.');if(s.phase!=='fulfill')return advance(s,ms);const elapsed=s.dayElapsed||0,step=Math.min(ms,Math.max(0,DAY_DURATION-elapsed)),events=advance(s,step);s.dayElapsed=Math.min(DAY_DURATION,elapsed+step);if(s.dayElapsed===DAY_DURATION){const report=close(s);events.push({type:'day-ended',report});}return events;}
function advance(s,ms,autoFulfill=false){
if(!Number.isFinite(ms)||ms<0||ms>3600000)throw Error('Nieprawidłowy krok czasu.');
const active=s.phase==='fulfill',live=active?ensureLive(s):{queue:[],nextIn:0,job:null},events=[];
function assign(){if(!active)return;if(live.job&&!s.orders.some(o=>o.id===live.job.id&&o.status==='new'))live.job=null;if(!live.job){const o=s.orders.find(o=>o.status==='new');if(o)live.job={id:o.id,elapsed:0};}}
if(active&&autoFulfill&&s.orders.some(o=>o.status==='packed'))events.push({type:'shipped',count:ship(s)});
assign();
while(ms>0){
const arrival=live.queue.length?live.nextIn:Infinity,packing=live.job?packingDuration(s)-live.job.elapsed:Infinity;
const trafficWait=active&&s.traffic&&s.traffic.elapsed<s.traffic.duration?s.traffic.nextIn:Infinity;const delivery=Math.min(Infinity,...s.deliveries.filter(d=>d.remainingMs!==undefined).map(d=>d.remainingMs));const step=Math.min(ms,arrival,packing,delivery,trafficWait);if(!Number.isFinite(step))break;
if(live.queue.length)live.nextIn=Math.max(0,live.nextIn-step);if(live.job)live.job.elapsed+=step;ms-=step;if(trafficWait!==Infinity)s.traffic.nextIn-=step;for(const d of s.deliveries)if(d.remainingMs!==undefined)d.remainingMs=Math.max(0,d.remainingMs-step);for(const d of s.deliveries.filter(d=>d.remainingMs===0)){s.stock[d.index].qty+=d.qty;s.stock[d.index].value=round(s.stock[d.index].value+d.value);log(s,"Dostawa dotarła: "+d.qty+" × "+PRODUCTS[d.index].name+".");events.push({type:"delivery",delivery:{...d}});}s.deliveries=s.deliveries.filter(d=>d.remainingMs!==0);
if(trafficWait!==Infinity&&s.traffic.nextIn<=0){trafficTick(s);events.push({type:'traffic'});}
if(live.queue.length&&live.nextIn<=0){
const planned=live.queue.shift(),st=s.stock[planned.index];if(planned.liveOffer)Object.assign(planned,offer(s,planned.index,planned.units,planned.useCoupon),{freeShipping:s.freeShipping,quality:s.prices[planned.index]/PRODUCTS[planned.index].price>1.3});
if(st.qty>=qty(planned)){const cost=round(st.value/st.qty*qty(planned));st.qty-=qty(planned);st.value=st.qty?round(st.value-cost):0;const order={...planned,id:s.nextId++,cost,status:'new'};s.orders.push(order);const channel=s.business?.channelStats?.find(c=>c.id===order.channel);if(channel){channel.accepted++;channel.orderedValue=round((channel.orderedValue||0)+order.price+(order.deliveryCharge||0));}if(s.traffic){const m=Math.min(Math.ceil(s.traffic.duration/60000)-1,Math.max(0,Math.floor((s.traffic.elapsed-1)/60000)));if(s.traffic.minutes[m])s.traffic.minutes[m].orders++;}events.push({type:'order',order});log(s,'Nowe zamówienie #'+order.id+' · '+PRODUCTS[order.index].name+'.');}else s.lost++;
live.nextIn=live.queue.length?delay(s):0;
}
if(live.job&&live.job.elapsed>=packingDuration(s)){const id=live.job.id;pack(s,id);events.push({type:'packed',id});if(autoFulfill)events.push({type:'shipped',count:ship(s)});live.job=null;}
assign();if(!hasDemand(s)&&!live.job&&!s.deliveries.some(d=>d.remainingMs!==undefined))break;
}
return events;
}
function pack(s,id){if(s.phase!=='fulfill')throw Error('Otwórz najpierw dzień sprzedaży.');const o=s.orders.find(o=>o.id===id&&o.status==='new');if(!o)throw Error('Brak zamówienia do pakowania.');o.status='packed';s.packedToday++;}
function ship(s){if(s.phase!=='fulfill')throw Error('Kurier przyjeżdża w otwartym dniu.');const pending=s.orders.filter(o=>o.status==='packed');if(!pending.length)throw Error('Najpierw spakuj zamówienie.');
for(const o of pending){const sales=round(o.price+(o.deliveryCharge??(o.freeShipping?0:9))),shipping=o.shippingCost??11,packaging=o.packagingCost??0,fee=round(sales*(o.paymentRate??.02)+(o.paymentFixed??0));s.cash=round(s.cash+sales-shipping-packaging-fee);entry(s,'sales',sales);entry(s,'cogs',o.cost);entry(s,'shipping',shipping);entry(s,'packaging',packaging);entry(s,'fees',fee);o.status='shipped';s.shipped++;s.returns.push({...o,due:s.day+2,sales});const channel=s.business?.channelStats?.find(c=>c.id===o.channel);if(channel){channel.orders++;channel.sales=round(channel.sales+sales);channel.contribution=round(channel.contribution+sales-o.cost-shipping-packaging-fee);}if(o.returnRoll>.15)review(s,5,'Dobrze zapakowane kosmetyki i szybka wysyłka.');}
s.tutorial=Math.max(s.tutorial,4);log(s,'Kurier odebrał '+pending.length+' paczek.');return pending.length;}
function settleTax(s){migrate(s);const result=round(profit(s.ledger)+(s.ledger.tax||0)),offset=Math.min(s.tax.loss,Math.max(0,result));s.tax.loss=round(s.tax.loss-offset+Math.max(0,-result));const due=round(Math.max(0,result-offset)*.19);entry(s,'tax',due);s.cash=round(s.cash-due);}
function close(s){if(s.phase!=='fulfill')throw Error('Dzień nie jest otwarty.');for(const o of s.orders.filter(o=>o.status!=='shipped')){s.stock[o.index].qty+=qty(o);s.stock[o.index].value=round(s.stock[o.index].value+o.cost);o.status='cancelled';review(s,2,'Zamówienie nie zostało wysłane. Anuluję zakup.');}const daily=s.business?.dayCosts;const fixed=daily?daily.rent:LEVELS[s.level].rent+(s.worker?95:0);entry(s,'fixed',fixed);s.cash=round(s.cash-fixed);if(daily){for(const [key,amount] of [['agency',daily.agencyFixed],['payroll',daily.payroll],['software',daily.software]]){entry(s,key,amount);s.cash=round(s.cash-amount);}const b=s.business;b.seoAge++;b.seoPoints=round(b.seoPoints*.997);if(b.seoBudget>0)b.seoPending.push({amount:b.seoBudget,due:s.day+30});b.brand=round(Math.min(300,b.brand*.995+b.budgets.articles/350*.7+s.orders.filter(o=>o.status==='shipped').length*.03));delete b.dayCosts;}creditDay(s);settleTax(s);s.phase='report';s.live={queue:[],nextIn:0,job:null};const result={day:s.day,...s.ledger,profit:round(profit(s.ledger)),orders:s.orders.filter(o=>o.status==='shipped').length,visits:s.visits};const shipped=s.orders.filter(o=>o.status==='shipped');result.units=shipped.reduce((n,o)=>n+qty(o),0);result.productSales=round(shipped.reduce((n,o)=>n+o.price,0));result.discounts=round(shipped.reduce((n,o)=>n+(o.discount||0),0));result.promotions=[...new Set(shipped.map(o=>o.promo||'unknown'))];if(s.traffic)result.channels=JSON.parse(JSON.stringify(s.business.channelStats));s.history.push(result);s.tutorial=Math.max(s.tutorial,5);log(s,'Wynik dnia '+s.day+': '+result.profit+' zł.');return result;}
function next(s){if(s.phase!=='report')throw Error('Najpierw podsumuj dzień.');s.day++;s.dayElapsed=0;delete s.traffic;if(s.business){const b=s.business;for(const investment of (b.seoPending||[]).filter(x=>x.due<=s.day))b.seoPoints=round(b.seoPoints+investment.amount);b.seoPending=(b.seoPending||[]).filter(x=>x.due>s.day);delete b.channelStats;}s.ledger=empty();s.orders=[];s.live={queue:[],nextIn:0,job:null};s.phase='plan';for(const d of s.deliveries.filter(d=>d.due<=s.day)){s.stock[d.index].qty+=d.qty;s.stock[d.index].value=round(s.stock[d.index].value+d.value);log(s,'Dostawa dotarła: '+d.qty+' × '+PRODUCTS[d.index].name+'.');}s.deliveries=s.deliveries.filter(d=>d.remainingMs!==undefined||d.due>s.day);for(const o of s.returns.filter(o=>o.due<=s.day)){if(o.returnRoll<(o.quality?.16:.07)){entry(s,'refunds',o.sales);const handling=o.returnHandling??6;entry(s,'returnFees',handling);s.cash=round(s.cash-o.sales-handling);review(s,3,'Produkt nie spełnił oczekiwań. Zwrot został rozliczony.');log(s,'Zwrot #'+o.id+': −'+(o.sales+handling)+' zł. Otwarty kosmetyk nie wraca do sprzedaży.');}}s.returns=s.returns.filter(o=>o.due>s.day);}
function upgrade(s){if(s.phase!=='plan')throw Error('Rozbudowę zaplanuj przed otwarciem dnia.');if(s.level>=2)throw Error('Masz największy magazyn MVP.');const cost=LEVELS[s.level+1].upgrade;if(s.shipped<(s.level===0?20:100))throw Error('Najpierw wyślij '+(s.level===0?20:100)+' zamówień.');if(s.cash<cost)throw Error('Brak środków na przeprowadzkę.');s.cash=round(s.cash-cost);entry(s,'setup',cost);s.level++;log(s,'Nowa siedziba: '+LEVELS[s.level].name+'!');}
function hire(s){if(s.phase!=='plan')throw Error('Zespół zmienisz przed otwarciem dnia.');if(s.level<1)throw Error('Magazynier wymaga Pracowni marki.');s.worker=!s.worker;}

// Fictional credit scenario, with market references and explicit simplifications in REALIA.
const CREDIT={annualRate:12,feePercent:2,lateRate:14.5,earlyPercent:3,earlyMinimum:100};
function debt(s){const l=s.credit?.loan;return l?round(l.principal+l.accrued+l.interestDue):0;}
function creditLimit(s){if(s.cash<0||s.credit?.loan&&debt(s)>0)return 0;const recent=s.history.slice(-7);return s.day>=31&&recent.length===7&&recent.reduce((n,h)=>n+h.profit,0)>0?15000:5000;}
function loanQuote(amount,months){if(!Number.isInteger(amount)||amount<1000||amount>15000||amount%500!==0||![3,6,12].includes(months))throw Error('Kwota: 1000–15 000 zł, co 500 zł; okres: 3, 6 lub 12 miesięcy.');const fee=round(amount*CREDIT.feePercent/100),principal=round(amount/months),schedule=[];let left=amount;for(let n=0;n<months;n++){const capital=n===months-1?left:Math.min(left,principal),interest=round(left*CREDIT.annualRate/100*30/365);schedule.push({month:n+1,principal:capital,interest,payment:round(capital+interest)});left=round(left-capital);}return {amount,months,fee,net:round(amount-fee),schedule,totalInterest:round(schedule.reduce((n,x)=>n+x.interest,0)),totalCost:round(fee+schedule.reduce((n,x)=>n+x.interest,0))};}
function borrow(s,amount,months){if(s.phase==='report')throw Error('Przejdź do kolejnego dnia, aby podpisać umowę.');const q=loanQuote(amount,months);if(amount>creditLimit(s))throw Error('Kwota przekracza dostępny limit albo masz już aktywny kredyt.');migrate(s);s.credit.loan={initial:amount,principal:amount,months,rate:CREDIT.annualRate,fee:q.fee,capitalRate:q.schedule[0].principal,nextDue:s.day+29,installments:0,accrued:0,interestDue:0,principalDue:0,interestPaid:0,started:s.day};s.credit.borrowed=round(s.credit.borrowed+amount);s.cash=round(s.cash+q.net);entry(s,'loanFees',q.fee);log(s,'Kredyt: '+amount+' zł, wypłata '+q.net+' zł po prowizji. Pierwsza rata w dniu '+s.credit.loan.nextDue+'.');return q;}
function payDue(s){const l=s.credit?.loan;if(!l)return 0;let cash=Math.max(0,s.cash),interest=Math.min(cash,l.interestDue);cash=round(cash-interest);l.interestDue=round(l.interestDue-interest);l.interestPaid=round(l.interestPaid+interest);const capital=Math.min(cash,l.principalDue);l.principalDue=round(l.principalDue-capital);l.principal=round(l.principal-capital);s.credit.repaid=round(s.credit.repaid+capital);s.cash=round(s.cash-interest-capital);return round(interest+capital);}
function creditDay(s){const l=s.credit?.loan;if(!l||debt(s)===0)return;const interest=((l.principal-l.principalDue)*l.rate+l.principalDue*CREDIT.lateRate)/100/365;l.accrued=Math.round((l.accrued+interest)*1e8)/1e8;entry(s,'interest',round(l.accrued+ l.interestDue+l.interestPaid)-round((l.accrued-interest)+l.interestDue+l.interestPaid));if(s.day>=l.nextDue&&l.installments<l.months){l.installments++;const capital=l.installments===l.months?l.principal-l.principalDue:Math.min(l.capitalRate,l.principal-l.principalDue);l.principalDue=round(l.principalDue+capital);l.nextDue+=30;l.interestDue=round(l.interestDue+l.accrued);l.accrued=0;}if(l.installments===l.months&&l.accrued){l.interestDue=round(l.interestDue+l.accrued);l.accrued=0;}if(l.principalDue>0||l.interestDue>0){const paid=payDue(s);if(paid)log(s,'Spłata raty: '+paid+' zł. Pozostały kapitał '+l.principal+' zł.');if(l.principalDue>0||l.interestDue>0)log(s,'Zaległa rata: '+round(l.principalDue+l.interestDue)+' zł. Uzupełnij gotówkę w Finansowaniu.');}}
function settleDue(s){if(s.phase==='report')throw Error('Przejdź do kolejnego dnia, aby spłacić zaległość.');const paid=payDue(s);if(!paid)throw Error('Brak zaległości albo wolnej gotówki.');log(s,'Spłacono zaległość: '+paid+' zł.');return paid;}
function payoffQuote(s){const l=s.credit?.loan;if(!l||!debt(s))return null;const interest=round(l.accrued+l.interestDue),fee=l.installments<l.months&&l.principal>l.principalDue?Math.max(CREDIT.earlyMinimum,round((l.principal-l.principalDue)*CREDIT.earlyPercent/100)):0;return {principal:l.principal,interest,fee,total:round(l.principal+interest+fee)};}
function repay(s){if(s.phase==='report')throw Error('Spłatę zlecisz w kolejnym dniu.');const q=payoffQuote(s);if(!q)throw Error('Brak zadłużenia.');if(s.cash<q.total)throw Error('Brak gotówki na pełną spłatę.');const l=s.credit.loan;s.cash=round(s.cash-q.total);s.credit.repaid=round(s.credit.repaid+l.principal);l.interestPaid=round(l.interestPaid+q.interest);l.principal=0;l.principalDue=0;l.interestDue=0;l.accrued=0;entry(s,'loanFees',q.fee);log(s,'Kredyt spłacony w całości: '+q.total+' zł.');}
function lowStock(s){return PRODUCTS.flatMap((p,i)=>{const watched=s.stockWatch?.[i]||s.stock[i].qty>0||s.deliveries.some(d=>d.index===i);if(!watched)return [];const queued=(s.live?.queue||[]).filter(o=>o.index===i).reduce((n,o)=>n+qty(o),0),available=Math.max(0,s.stock[i].qty-queued),threshold=Math.max(5,config(s).promo.type==='bundle'?8:5),incoming=s.deliveries.filter(d=>d.index===i).reduce((n,d)=>n+d.qty,0);return available<=threshold?[{index:i,available,threshold,incoming,type:available===0?(incoming?'waiting':'empty'):'low'}]:[];});}
function validate(s){
const num=(n,min=0,max=1e12)=>Number.isFinite(n)&&n>=min&&n<=max;
const integer=(n,min=0,max=1e7)=>Number.isInteger(n)&&n>=min&&n<=max;
const arr=(v,max)=>Array.isArray(v)&&v.length<=max;
const entryOK=l=>l&&Object.keys(empty()).every(k=>num(l[k])||(EXTRA_COSTS.includes(k)&&l[k]===undefined));
const offerOK=o=>(o.liveOffer===undefined||typeof o.liveOffer==='boolean')&&(o.units===undefined||integer(o.units,1,3))&&(o.useCoupon===undefined||typeof o.useCoupon==='boolean')&&(o.qty===undefined||integer(o.qty,1,4))&&(o.channel===undefined||['organic',...CHANNELS.map(c=>c.id)].includes(o.channel))&&['basePrice','discount','deliveryCharge','shippingCost','packagingCost','paymentRate','paymentFixed','returnHandling'].every(k=>o[k]===undefined||num(o[k],0,2000));
const businessOK=b=>b===undefined||!!(b&&(b.planConfirmed===undefined||typeof b.planConfirmed==='boolean')&&b.budgets&&CHANNELS.every(c=>num(b.budgets[c.id],0,3000))&&b.budgets.articles%350===0&&typeof b.agency==='boolean'&&num(b.seoBudget,0,500)&&num(b.seoPoints)&&(b.seoPending===undefined||arr(b.seoPending,31)&&b.seoPending.every(x=>x&&num(x.amount,0,500)&&integer(x.due,1)))&&integer(b.seoAge)&&num(b.brand,0,300)&&b.promo&&['none','sale','coupon','bundle'].includes(b.promo.type)&&num(b.promo.percent,1,50)&&b.rates&&Object.keys(defaults().rates).every(k=>num(b.rates[k],0,20000))&&(b.dayCosts===undefined||['ads','agencyVariable','agencyFixed','payroll','software','rent'].every(k=>num(b.dayCosts[k])))&&(b.channelStats===undefined||arr(b.channelStats,6)&&b.channelStats.every(c=>['organic',...CHANNELS.map(x=>x.id)].includes(c.id)&&typeof c.name==='string'&&c.name.length<100&&['spend','visits','accepted','orders','sales'].every(k=>num(c[k]))&&num(c.contribution,-1e12)&&['plannedVisits','views','carts','checkouts','orderedValue','lost'].every(k=>c[k]===undefined||num(c[k])))));
const orderOK=o=>o&&integer(o.id,1001)&&integer(o.index,0,s.stock.length-1)&&num(o.price,.01,2000)&&num(o.cost)&&['new','packed','shipped','cancelled'].includes(o.status)&&typeof o.freeShipping==='boolean'&&typeof o.quality==='boolean'&&num(o.returnRoll,0,1)&&offerOK(o);
const liveOK=s=>s.live===undefined||!!(s.live&&arr(s.live.queue,160)&&s.live.queue.every(o=>o&&offerOK(o)&&integer(o.index,0,s.stock.length-1)&&num(o.price,.01,2000)&&typeof o.freeShipping==='boolean'&&typeof o.quality==='boolean'&&num(o.returnRoll,0,1))&&num(s.live.nextIn,0,50000)&&(s.live.queue.length?s.live.nextIn>0:s.live.nextIn===0)&&(s.live.job===null||(s.live.job&&integer(s.live.job.id,1001)&&num(s.live.job.elapsed,0,s.worker?9000:16000))));
const trafficOK=t=>t===undefined||!!(t&&[180000,300000].includes(t.duration)&&num(t.elapsed,0,t.duration)&&num(t.nextIn,0,1000)&&((t.elapsed<t.duration&&t.nextIn>0)||t.elapsed===t.duration)&&arr(t.sources,6)&&t.sources.every(c=>['organic',...CHANNELS.map(x=>x.id)].includes(c.id)&&integer(c.planned,0,100000)&&integer(c.served,0,c.planned)&&num(c.start,0,t.duration-1)&&num(c.cvr,0,1)&&num(c.variation,0,2)&&num(c.overlap,0,1))&&arr(t.products,PRODUCTS.length)&&[6,PRODUCTS.length].includes(t.products.length)&&t.products.every(c=>integer(c.views)&&integer(c.carts))&&arr(t.minutes,Math.ceil(t.duration/60000))&&t.minutes.every(c=>integer(c.visits)&&integer(c.orders)));
const creditOK=c=>c===undefined||!!(c&&num(c.borrowed)&&num(c.repaid)&&c.repaid<=c.borrowed&&(c.loan===null||c.loan&&integer(c.loan.initial,1000,15000)&&[3,6,12].includes(c.loan.months)&&num(c.loan.principal,0,c.loan.initial)&&c.loan.rate===12&&num(c.loan.fee)&&num(c.loan.capitalRate,0,c.loan.initial)&&integer(c.loan.nextDue,1)&&integer(c.loan.started,1)&&integer(c.loan.installments,0,c.loan.months)&&num(c.loan.accrued)&&num(c.loan.interestDue)&&num(c.loan.principalDue,0,c.loan.principal)&&num(c.loan.interestPaid)));
return !!(s&&(s.dayElapsed===undefined||num(s.dayElapsed,0,300000))&&(s.tax===undefined||s.tax&&num(s.tax.loss))&&Array.isArray(s.stock)&&(s.catalogRevision!==2||s.stock.length===PRODUCTS.length)&&(s.traffic===undefined||s.traffic?.products?.length===s.stock.length)&&(s.stockWatch===undefined||s.stockWatch?.length===s.stock.length)&&creditOK(s.credit)&&(s.stockWatch===undefined||arr(s.stockWatch,PRODUCTS.length)&&[6,PRODUCTS.length].includes(s.stockWatch.length)&&s.stockWatch.every(x=>typeof x==='boolean'))&&trafficOK(s.traffic)&&liveOK(s)&&businessOK(s.business)&&s.version===1&&integer(s.day,1)&&['plan','fulfill','report'].includes(s.phase)&&num(s.cash,-1e12)&&integer(s.level,0,2)&&integer(s.seed,0,4294967295)&&num(s.rating,1,5)&&integer(s.ratingCount,1)&&integer(s.shipped)&&integer(s.packedToday)&&integer(s.visits)&&integer(s.lost)&&integer(s.nextId,1001)&&integer(s.tutorial,0,5)&&typeof s.freeShipping==='boolean'&&typeof s.worker==='boolean'&&integer(s.campaign,0,3)&&arr(s.stock,PRODUCTS.length)&&[6,PRODUCTS.length].includes(s.stock.length)&&s.stock.every(x=>x&&integer(x.qty,0,1200)&&num(x.value))&&arr(s.prices,PRODUCTS.length)&&[6,PRODUCTS.length].includes(s.prices.length)&&s.prices.length===s.stock.length&&s.prices.every(x=>num(x,5,500))&&arr(s.orders,160)&&s.orders.every(orderOK)&&arr(s.deliveries,240)&&s.deliveries.every(d=>d&&integer(d.index,0,s.stock.length-1)&&integer(d.qty,1,1200)&&num(d.value)&&(d.remainingMs!==undefined?num(d.remainingMs,0,300000):integer(d.due,1)))&&arr(s.returns,320)&&s.returns.every(o=>orderOK(o)&&integer(o.due,1)&&num(o.sales))&&arr(s.reviews,25)&&s.reviews.every(r=>r&&integer(r.day,1)&&integer(r.stars,1,5)&&typeof r.text==='string'&&r.text.length<=1000)&&arr(s.log,12)&&s.log.every(x=>typeof x==='string'&&x.length<2000)&&arr(s.history,100000)&&s.history.every(h=>(h.units===undefined||integer(h.units))&&(h.productSales===undefined||num(h.productSales))&&(h.discounts===undefined||num(h.discounts))&&(h.promotions===undefined||arr(h.promotions,5)&&h.promotions.every(x=>['none','sale','coupon','bundle','unknown'].includes(x)))&&entryOK(h)&&integer(h.day,1)&&num(h.profit,-1e12)&&integer(h.orders)&&integer(h.visits)&&(h.channels===undefined||businessOK({...defaults(),channelStats:h.channels})))&&entryOK(s.ledger)&&entryOK(s.total));
}
return {organicGrowth,DAY_DURATION,tick,CREDIT,debt,creditLimit,loanQuote,borrow,payDue,settleDue,payoffQuote,repay,lowStock,reach,audience,conversion,boost,hasDemand,KNEES,PRODUCTS,LEVELS,CAMPAIGNS,CHANNELS,defaults,migrate,config,settings,spend,dayCosts,offer,purchaseEconomics,unitEconomics,qty,create,profit,round,used,buy,price,open,advance,ensureLive,packingDuration,pack,ship,close,next,upgrade,hire,validate};
});


