const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('./engine.js');
const finish=s=>{s.orders.filter(o=>o.status==='new').forEach(o=>E.pack(s,o.id));if(s.orders.some(o=>o.status==='packed'))E.ship(s);E.close(s);};
function invariant(s){const inventory=s.stock.reduce((a,b)=>a+b.value,0)+s.deliveries.reduce((a,b)=>a+b.value,0)+s.orders.filter(o=>o.status==='new'||o.status==='packed').reduce((a,b)=>a+b.cost,0);assert.ok(Math.abs(s.cash-(10000+E.profit(s.total)-inventory))<.05,JSON.stringify({cash:s.cash,profit:E.profit(s.total),inventory}));assert.ok(s.stock.every(x=>x.qty>=0&&x.value>=0));assert.ok(E.used(s)<=E.LEVELS[s.level].capacity);}
test('Purchase changes cash and inventory, not profit',()=>{const s=E.create();E.buy(s,0,10);assert.equal(s.cash,9760);assert.equal(s.stock[0].qty,10);assert.equal(E.profit(s.ledger),0);invariant(s);});
test('Supplier MOQ, finite quantity, funds and capacity enforced atomically',()=>{const s=E.create();for(const args of [[0,0,0],[0,2,0],[0,10,1],[0,151,0],[0,NaN,0],[0,2.5,0],[6,5,0]]){assert.throws(()=>E.buy(s,...args));}assert.equal(s.cash,10000);s.cash=1;assert.throws(()=>E.buy(s,0,10));});
test('Wholesale arrives next day and weighted purchase cost is conserved',()=>{const s=E.create();E.buy(s,0,20,1);E.buy(s,0,10,0);assert.equal(s.deliveries.length,1);s.campaign=0;E.open(s);finish(s);E.next(s);assert.equal(s.deliveries.length,0);assert.ok(s.stock[0].qty>=20);invariant(s);});
test('Prices validate; campaign is charged only once',()=>{const s=E.create();assert.throws(()=>E.price(s,0,NaN));assert.throws(()=>E.price(s,0,301));E.open(s);const cash=s.cash;assert.throws(()=>E.open(s));assert.equal(s.cash,cash);assert.throws(()=>E.price(s,0,50));});
test('Complete loop creates paid sales and exact COGS, prevents double shipping',()=>{const s=E.create();E.buy(s,0,25);E.open(s);assert.ok(s.orders.length>0);assert.equal(s.ledger.sales,0);invariant(s);s.orders.forEach(o=>E.pack(s,o.id));const n=E.ship(s);assert.equal(s.ledger.sales,n*68);assert.equal(s.ledger.cogs,n*24);assert.equal(s.ledger.shipping,n*11);assert.throws(()=>E.ship(s));invariant(s);E.close(s);assert.equal(s.ledger.fixed,35);E.next(s);E.buy(s,1,5);invariant(s);});
test('Unfulfilled orders return stock and reduce reputation with no phantom revenue',()=>{const s=E.create();E.buy(s,0,20);E.open(s);E.pack(s,s.orders[0].id);E.close(s);assert.equal(s.stock[0].qty,20);assert.equal(E.used(s),20);assert.equal(s.ledger.sales,0);assert.ok(s.rating<4.6);assert.ok(s.orders.every(o=>o.status==='cancelled'));invariant(s);});
test('High turnover can produce a loss at poor prices with ads and free delivery',()=>{const s=E.create();E.buy(s,0,100);E.price(s,0,25);s.freeShipping=true;s.campaign=3;E.open(s);finish(s);assert.ok(s.ledger.sales>=500);assert.ok(E.profit(s.ledger)<0);invariant(s);});
test('Return refunds full payment two days later, adds handling; cosmetics cannot restock',()=>{const s=E.create();E.buy(s,0,20);E.open(s);s.orders.forEach(o=>o.returnRoll=0);finish(s);const n=s.shipped,qty=s.stock[0].qty;E.next(s);assert.equal(s.ledger.refunds,0);s.campaign=0;E.open(s);E.close(s);E.next(s);assert.equal(s.ledger.refunds,n*68);assert.equal(s.ledger.returnFees,n*6);assert.equal(s.stock[0].qty,qty);invariant(s);});
test('Upgrades gated; hiring changes capacity of work and fixed costs',()=>{const s=E.create();assert.throws(()=>E.upgrade(s));assert.throws(()=>E.hire(s));E.buy(s,0,100);s.campaign=2;E.open(s);finish(s);E.next(s);assert.ok(s.shipped>=20);E.upgrade(s);assert.equal(s.level,1);E.hire(s);E.open(s);assert.equal(s.orders.filter(o=>o.status==='packed').length,Math.min(s.orders.length,20));finish(s);assert.equal(s.ledger.fixed,180);invariant(s);});
test('Organic recovery is possible with negative cash and existing inventory',()=>{const s=E.create();E.buy(s,0,20);s.cash=-10;s.campaign=0;E.open(s);assert.ok(s.orders.length);finish(s);assert.ok(s.cash>-10);});
test('Save round trip retains deterministic state',()=>{const s=E.create();E.buy(s,0,25);const restored=JSON.parse(JSON.stringify(s));assert.ok(E.validate(restored));E.open(s);E.open(restored);assert.deepEqual(s,restored);assert.equal(E.validate({version:9}),false);});
test('30-day reinvestment and upgrade simulation balances all assets and profit',()=>{const s=E.create();for(let day=1;day<=30;day++){if(s.level<2&&s.shipped>=(s.level===0?20:100)&&s.cash>E.LEVELS[s.level+1].upgrade+2500)E.upgrade(s);for(let i=0;i<6;i++){if(s.stock[i].qty<20&&E.used(s)+20<=E.LEVELS[s.level].capacity&&s.cash>E.PRODUCTS[i].cost*20+600)E.buy(s,i,20,day%3===0?1:0);}s.campaign=s.level?2:1;invariant(s);E.open(s);invariant(s);finish(s);invariant(s);E.next(s);invariant(s);}assert.equal(s.level,2);assert.ok(s.cash>10000);console.log('30-day outcome:',s.cash,'cash;',s.shipped,'orders;',E.round(E.profit(s.total)),'profit');});
test('Reject malformed nested saves without crashing or trusting injected markup',()=>{const base=E.create();for(const change of [s=>s.reviews=[{day:'<img>',stars:9,text:'x'}],s=>s.orders=[null],s=>s.deliveries=[{index:99,qty:2,value:10,due:2}],s=>s.seed='bad',s=>s.ledger.sales=Infinity,s=>s.prices[0]=-1,s=>s.history=[{}]]){const s=JSON.parse(JSON.stringify(base));change(s);assert.equal(E.validate(s),false);}assert.ok(E.validate(base));});
