const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('./engine.js');
const drain=s=>{for(let n=0;n<200&&(s.live?.queue.length||s.orders.some(o=>o.status==='new'));n++)E.advance(s,30000);};
const finish=s=>{drain(s);if(s.orders.some(o=>o.status==='packed'))E.ship(s);E.close(s);};
function balance(s){const assets=s.stock.reduce((a,b)=>a+b.value,0)+s.deliveries.reduce((a,b)=>a+b.value,0)+s.orders.filter(o=>['new','packed'].includes(o.status)).reduce((a,b)=>a+b.cost,0);assert.ok(Math.abs(s.cash-(10000+E.profit(s.total)-assets))<.05);assert.ok(s.stock.every(x=>x.qty>=0&&x.value>=0));assert.ok(E.used(s)<=E.LEVELS[s.level].capacity);assert.ok(E.validate(s));}
function stocked(){const s=E.create();E.buy(s,0,25);return s;}
test('Purchase changes cash and assets, not P&L; validates minimum, capacity, funds',()=>{const s=stocked();assert.equal(s.cash,9400);assert.equal(E.profit(s.total),0);for(const args of [[0,2],[0,151],[0,NaN],[0,2.5],[6,5],[0,10,1]])assert.throws(()=>E.buy(s,...args));balance(s);});
test('Opening charges one campaign; leaves all stock available until actual arrival',()=>{const s=stocked();E.open(s);assert.equal(s.orders.length,0);assert.equal(s.stock[0].qty,25);assert.ok(s.live.queue.length>0);assert.equal(s.ledger.ads,60);assert.throws(()=>E.open(s));balance(s);});
test('Every inter-arrival delay is 20–30 seconds and varies',()=>{const s=stocked();E.open(s);const delays=[];while(s.live.queue.length){const delay=s.live.nextIn;delays.push(delay);assert.ok(delay>=20000&&delay<=30000);const before=s.orders.length;E.advance(s,delay-1);assert.equal(s.orders.length,before);const events=E.advance(s,1);assert.equal(events.filter(e=>e.type==='order').length,1);assert.equal(s.orders.length,before+1);}assert.ok(new Set(delays).size>1);balance(s);});
test('Arrival reserves exactly one item and no revenue; pack finishes only after 16 seconds',()=>{const s=stocked();E.open(s);E.advance(s,s.live.nextIn);assert.equal(s.stock[0].qty,24);assert.equal(s.ledger.sales,0);assert.equal(s.live.job.elapsed,0);E.advance(s,15999);assert.equal(s.orders[0].status,'new');const events=E.advance(s,1);assert.equal(s.orders[0].status,'packed');assert.equal(events.filter(e=>e.type==='packed').length,1);balance(s);});
test('Hired worker shortens packing to 9 seconds, no instant bulk packing',()=>{const s=stocked();s.level=1;s.worker=true;E.open(s);assert.equal(s.orders.length,0);E.advance(s,s.live.nextIn);E.advance(s,8999);assert.equal(s.orders[0].status,'new');E.advance(s,1);assert.equal(s.orders[0].status,'packed');});
test('Manual help cannot double-pack or duplicate counters after automatic work',()=>{const s=stocked();E.open(s);E.advance(s,s.live.nextIn);E.advance(s,4000);E.pack(s,s.orders[0].id);E.advance(s,12000);assert.equal(s.packedToday,1);assert.throws(()=>E.pack(s,s.orders[0].id));balance(s);});
test('Shipping books exact COGS, fees and cash only once',()=>{const s=stocked();E.open(s);drain(s);const n=E.ship(s);assert.equal(s.ledger.sales,n*68);assert.equal(s.ledger.cogs,n*24);assert.equal(s.ledger.shipping,n*11);assert.throws(()=>E.ship(s));balance(s);});
test('Closing early discards future demand without reserving stock or bad reviews',()=>{const s=stocked();E.open(s);E.close(s);assert.equal(s.stock[0].qty,25);assert.equal(s.rating,4.6);assert.equal(s.live.queue.length,0);assert.equal(E.advance(s,30000).length,0);balance(s);});
test('Closing cancels accepted orders, restores inventory, reduces reputation, stops job',()=>{const s=stocked();E.open(s);E.advance(s,s.live.nextIn+5000);E.close(s);assert.equal(s.orders[0].status,'cancelled');assert.equal(s.stock[0].qty,25);assert.equal(E.used(s),25);assert.ok(s.rating<4.6);assert.equal(s.live.job,null);balance(s);});
test('Wholesale arrives tomorrow with conserved weighted inventory value',()=>{const s=stocked();E.buy(s,0,20,1);E.open(s);finish(s);E.next(s);assert.equal(s.deliveries.length,0);assert.ok(s.stock[0].qty>=20);balance(s);});
test('High revenue still produces loss with low prices, advertising and free shipping',()=>{const s=E.create();E.buy(s,0,100);E.price(s,0,25);s.freeShipping=true;s.campaign=3;E.open(s);finish(s);assert.ok(s.ledger.sales>=500);assert.ok(E.profit(s.ledger)<0);balance(s);});
test('Returns two days later refund full payment, add handling, do not restore opened product',()=>{const s=stocked();E.open(s);s.live.queue.forEach(o=>o.returnRoll=0);finish(s);const n=s.shipped,qty=s.stock[0].qty;E.next(s);assert.equal(s.ledger.refunds,0);s.campaign=0;E.open(s);E.close(s);E.next(s);assert.equal(s.ledger.refunds,n*68);assert.equal(s.ledger.returnFees,n*6);assert.equal(s.stock[0].qty,qty);balance(s);});
test('Old v1 saves load and existing orders enter automatic packing',()=>{const s=stocked();E.open(s);E.advance(s,s.live.nextIn);delete s.live;const saved=JSON.parse(JSON.stringify(s));assert.ok(E.validate(saved));E.advance(saved,16000);assert.equal(saved.orders[0].status,'packed');assert.equal(saved.live.queue.length,0);balance(saved);});
test('Roundtrip preserves pending arrivals, random state and partial packing exactly',()=>{const s=stocked();E.open(s);E.advance(s,s.live.nextIn+5000);const other=JSON.parse(JSON.stringify(s));assert.ok(E.validate(other));assert.deepEqual(E.advance(s,30000),E.advance(other,30000));assert.deepEqual(s,other);balance(s);});
test('Reject invalid or unbounded runtime state and malformed imports',()=>{const base=stocked();E.open(base);for(const change of [s=>s.live.nextIn=-1,s=>s.live.nextIn=Infinity,s=>s.live.queue=[{index:99}],s=>s.live.job={id:1001,elapsed:99999},s=>s.reviews=[{day:'<img>',stars:9,text:'x'}],s=>s.orders=[null],s=>s.seed='bad',s=>s.ledger.sales=Infinity]){const s=JSON.parse(JSON.stringify(base));change(s);assert.equal(E.validate(s),false);}assert.throws(()=>E.advance(base,-1));assert.throws(()=>E.advance(base,Infinity));assert.throws(()=>E.price(base,0,50));});
test('Paused/no-time and non-selling phases do not advance orders or charge again',()=>{const s=stocked();E.open(s);const copy=JSON.stringify(s);E.advance(s,0);assert.equal(JSON.stringify(s),copy);E.close(s);const report=JSON.stringify(s);E.advance(s,60000);assert.equal(JSON.stringify(s),report);E.next(s);const plan=JSON.stringify(s);E.advance(s,60000);assert.equal(JSON.stringify(s),plan);});
test('Organic sales allow recovery with negative cash',()=>{const s=stocked();s.cash=-10;s.campaign=0;E.open(s);finish(s);assert.ok(s.cash>-10);});
test('30-day reinvestment, upgrades and timed fulfillment balance all assets',()=>{const s=E.create();assert.throws(()=>E.upgrade(s));assert.throws(()=>E.hire(s));for(let day=1;day<=30;day++){if(s.level<2&&s.shipped>=(s.level===0?20:100)&&s.cash>E.LEVELS[s.level+1].upgrade+2500)E.upgrade(s);for(let i=0;i<6;i++)if(s.stock[i].qty<20&&E.used(s)+20<=E.LEVELS[s.level].capacity&&s.cash>E.PRODUCTS[i].cost*20+600)E.buy(s,i,20,day%3===0?1:0);s.campaign=s.level?2:1;E.open(s);balance(s);while(s.live.queue.length||s.orders.some(o=>o.status==='new')){E.advance(s,30000);balance(s);}finish(s);balance(s);E.next(s);balance(s);}assert.equal(s.level,2);assert.ok(s.cash>10000);console.log('30 days:',s.shipped,'orders;',s.cash,'cash');});
