/* Cash, inventory and credit are separate balances. */
function cashBridgeView(){const c=E.cashBridge(game);return '<section class="note"><h3>Gdzie jest gotówka z zysku?</h3><p>Zysk uwzględnia koszt sprzedanego towaru. Za zapasy płacisz wcześniej, więc rentowna firma może nie mieć gotówki na kolejne zakupy.</p>'+[['Kapitał startowy',c.initial],['Zysk / strata od początku',c.result],['Niespłacony kapitał kredytu',c.principal],['Odsetki w wyniku, jeszcze nieopłacone',c.interest],['Towar na regałach (cena zakupu)',-c.stock],['Opłacone dostawy w drodze',-c.deliveries],['Towar w niezrealizowanych zamówieniach',-c.reserved],['Gotówka wynikająca z rozliczenia',c.expected],['Gotówka operacyjna',game.cash]].map(([label,value])=>'<div class="ledger-row"><span>'+label+'</span><b>'+money(value)+'</b></div>').join('')+(Math.abs(c.gap)>.05?'<p class="negative">Różnica w starszym zapisie: '+money(c.gap)+'. Tego salda nie da się wyjaśnić obecnymi zapisami księgowymi.</p>':'')+'<p>Rezerwacje nie są liczone drugi raz w zapasach. Wpływy za te zamówienia otrzymasz przy wysyłce. Kredyt zwiększa gotówkę, ale nie zysk.</p></section>';}
let topupAmount=5000;
function topupView(){const l=game.credit?.loan;if(!l||!E.debt(game))return '';const a=E.creditAssessment(game),valid=Number.isInteger(topupAmount)&&topupAmount>=1000&&topupAmount%500===0&&topupAmount<=a.limit,fee=E.round(topupAmount*.02),capital=E.round((l.principal+topupAmount)/a.months);return '<section class="note"><h3>Dobierz środki do aktywnego kredytu</h3><p>Łączna zdolność: <b>'+money(a.totalLimit)+'</b> · obecny dług: '+money(a.existingDebt)+' · dodatkowo dostępne: <b>'+money(a.limit)+'</b>.</p><label>Dodatkowa kwota (zł)<input id="topup-amount" type="number" min="1000" max="'+a.limit+'" step="500" value="'+topupAmount+'"></label><p>Wypłata po prowizji 2%: '+money(topupAmount-fee)+'. Prowizja: '+money(fee)+'. Oprocentowanie pozostaje 12% rocznie. Pozostało '+a.months+' rat; następna w dniu '+l.nextDue+'. Termin spłaty nie zmienia się.</p><p>Po zwiększeniu część kapitałowa raty: około <b>'+money(capital)+'</b> + odsetki od aktualnego zadłużenia. Dług kapitałowy wzrośnie do '+money(l.principal+topupAmount)+'.</p><button id="topup-credit" class="primary" '+(!valid||game.phase==='report'?'disabled':'')+'>Dobierz '+money(topupAmount)+' kredytu</button></section>';}
const liquidityFinanceView=financeView;financeView=()=>cashBridgeView()+liquidityFinanceView();
const liquidityFundingView=fundingView;fundingView=()=>liquidityFundingView()+(game.phase==='bankrupt'?'':topupView()+cashBridgeView());
const noCampaignBox=document.createElement('div');noCampaignBox.className='note';noCampaignBox.innerHTML='<button class="secondary" id="open-no-campaign">Otwórz dzień bez płatnych kampanii</button><small>Ustawia budżety reklam i SEO na 0. Możesz wysyłać zaległości; ruch organiczny i koszty stałe pozostają. Budżety później ustawisz ponownie w Marketingu.</small>';$('main-action').after(noCampaignBox);
const liquidityRefresh=window.refreshLiveUI;window.refreshLiveUI=function(){liquidityRefresh?.();noCampaignBox.hidden=game.phase!=='plan';};
document.addEventListener('change',e=>{if(e.target.id==='topup-amount'){topupAmount=Number(e.target.value);render();}});
document.addEventListener('click',e=>{if(e.target.closest('#topup-credit'))action(()=>{E.borrow(game,topupAmount,game.credit.loan.months);toast('Dodatkowe środki są na koncie. Raty wzrosły; termin spłaty pozostał bez zmian.');});if(e.target.closest('#open-no-campaign'))action(()=>{E.openWithoutCampaign(game);toast('Dzień otwarty. Budżety płatnych kampanii i SEO wynoszą teraz 0 zł.');});});
window.refreshLiveUI();

const fundingSuggestion=document.createElement('section');fundingSuggestion.className='note';fundingSuggestion.id='funding-suggestion';fundingSuggestion.hidden=true;document.querySelector('.game-grid').before(fundingSuggestion);
const fundingSuggestionRefresh=window.refreshLiveUI;window.refreshLiveUI=function(){fundingSuggestionRefresh?.();const costs=E.dayCosts(game),required=game.phase==='plan'?E.round(costs.ads+costs.agencyVariable):0,shortfall=E.round(Math.max(0,required-game.cash)),visible=['plan','fulfill'].includes(game.phase)&&shortfall>0;fundingSuggestion.hidden=!visible;if(!visible)return;const a=E.creditAssessment(game),amount=Math.min(a.limit,Math.max(1000,Math.ceil(shortfall/.98/500)*500)),html='<h3>Brakuje '+money(shortfall)+' gotówki</h3><p>'+ (game.phase==='plan'?'Możesz otworzyć dzień z obecnymi kampaniami. Ich koszty obniżą saldo poniżej zera.':'Dzień działa dalej. Ujemne saldo oznacza niedobór gotówki, który mogą pokryć wpływy z wysyłek lub finansowanie.')+'</p>'+(a.limit?'<p>Masz zdolność na dodatkowe <b>'+money(a.limit)+'</b>. Proponowana kwota: '+money(amount)+' (wypłata po prowizji: '+money(E.round(amount*.98))+').'+(amount*.98<shortfall?' Ten limit nie pokryje całego niedoboru.':'')+'</p><button id="suggest-credit" class="secondary">'+(E.debt(game)>0?'Dobierz kredyt':'Sprawdź kredyt')+' →</button>':'<p>Obecnie brak zdolności kredytowej. Możesz nadal realizować zamówienia lub ograniczyć kampanie.</p>');if(fundingSuggestion.innerHTML!==html)fundingSuggestion.innerHTML=html;};
document.addEventListener('click',e=>{if(!e.target.closest('#suggest-credit'))return;const c=E.dayCosts(game),gap=Math.max(0,(game.phase==='plan'?c.ads+c.agencyVariable:0)-game.cash),a=E.creditAssessment(game),amount=Math.min(a.limit,Math.max(1000,Math.ceil(gap/.98/500)*500));if(!a.limit)return;topupAmount=amount;loanAmount=amount;loanMonths=12;go('funding');});
window.refreshLiveUI();
