/* First-session guidance and mobile controls; progression uses real saved results. */
let journeyHTML='',journeyGame=null,knownMilestones=new Set();
function milestones(){return [{id:'first',label:'Pierwsza paczka',value:game.shipped,target:1},{id:'five',label:'5 wysyłek',value:game.shipped,target:5},{id:'profit',label:'Dzień na plusie',value:game.history.filter(h=>h.profit>0).length,target:1},{id:'twenty',label:'20 wysyłek',value:game.shipped,target:20},{id:'warehouse',label:'Większy magazyn',value:game.level,target:1}];}
window.refreshJourney=function(){const goals=milestones(),next=goals.find(x=>x.value<x.target),fresh=game.tutorial===0&&E.used(game)===0&&game.day===1,stock=game.stock.reduce((n,x)=>n+x.qty,0);if(journeyGame!==game){journeyGame=game;knownMilestones=new Set(goals.filter(g=>g.value>=g.target).map(g=>g.id));}for(const g of goals)if(g.value>=g.target&&!knownMilestones.has(g.id)){knownMilestones.add(g.id);toast('Cel osiągnięty: '+g.label+'!');}
let title,copy,cta='',button='';if(fresh){title='Twoje pierwsze 10 minut';copy='Zacznij od dwóch kosmetyków. Podczas dostawy ustaw ceny i marketing, a potem obsłuż pierwszych klientów.';cta='Zestaw startowy · 2600 zł';button='starter-kit';}else if(game.phase==='plan'&&!stock&&game.deliveries.length){title='Towar jest w drodze';copy='Wykorzystaj oczekiwanie: sprawdź ceny i zapisz plan marketingu. Kampanię uruchomisz, gdy towar dotrze na regał.';cta='Ustaw marketing';button='guide-marketing';}else if(game.phase==='plan'&&!stock){title='Uzupełnij towar przed otwarciem';copy='Na regałach nie ma produktów do sprzedaży. Zamów nową dostawę, a w czasie oczekiwania przygotuj ceny i marketing.';cta='Zamów towar';button='guide-prices';}else if(game.phase==='plan'){title=E.config(game).planConfirmed?'Sklep gotowy do otwarcia':'Ustal budżet na klientów';copy=E.config(game).planConfirmed?'Sprawdź marżę i otwórz dzień. Pakowanie jest automatyczne, a wysyłkę zlecasz Ty.':'Na początek możesz zachować Google Ads 150 zł. Obsługa agencji i pozostałe koszty są pokazane przed startem.';cta=E.config(game).planConfirmed?'Sprawdź ceny':'Wybierz marketing';button=E.config(game).planConfirmed?'guide-prices':'guide-marketing';}else if(game.phase==='fulfill'){title='Zbuduj rytm swojego sklepu';copy='Przyjmuj klientów, wysyłaj spakowane paczki i uzupełniaj zapasy. Ceny oraz promocje możesz zmieniać podczas sprzedaży.';}else{title='Zdecyduj, co poprawić jutro';copy='Sprawdź, ile zostało po towarze, reklamie i kosztach firmy. Zmieniaj jedną rzecz naraz, aby zobaczyć jej wpływ.';cta='Zobacz analitykę';button='guide-analytics';}
const html='<div class="journey-card"><div><span class="eyebrow">'+(next?'NASTĘPNY CEL: '+next.label:'WSZYSTKIE CELE STARTOWE ZDOBYTE')+'</span><h2>'+title+'</h2><p>'+copy+'</p></div>'+(cta?'<button id="'+button+'" class="primary" '+(fresh&&(game.cash<2600||E.used(game)+40>E.LEVELS[game.level].capacity)?'disabled':'')+'>'+cta+'</button>':'')+'<div class="milestones">'+goals.map(g=>'<span class="'+(g.value>=g.target?'earned':'')+'">'+(g.value>=g.target?'✓ ':Math.min(g.value,g.target)+'/'+g.target+' ')+g.label+'</span>').join('')+'</div></div>';if(html!==journeyHTML){$('journey').innerHTML=html;journeyHTML=html;}
if(game.phase==='plan'&&!stock&&game.deliveries.length&&E.config(game).planConfirmed){$('main-action').disabled=true;$('main-action').textContent='Czekamy na pierwszą dostawę…';$('action-note').textContent='Kampania ruszy po dostawie — budżet jeszcze nie jest wydany.';}
if(game.phase==='plan'&&!stock&&!game.deliveries.length&&E.config(game).planConfirmed&&game.tutorial>0)$('main-action').textContent='Zamów towar przed otwarciem →';
const picker=$('section-picker');if(!picker.options.length)picker.innerHTML=[['products','Produkty i ceny'],['orders','Zamówienia'],['marketing','Marketing'],['promotions','Promocje'],['analytics','Analityka'],['costs','Koszty'],['finance','Wynik finansowy'],['funding','Finansowanie'],['growth','Rozwój'],['reviews','Opinie']].map(([id,label])=>'<option value="'+id+'">'+label+'</option>').join('');picker.value=tab;};
window.refreshMobileControls=function(){const source=$('main-action'),target=$('mobile-main');target.disabled=source.disabled;target.textContent=source.textContent;$('mobile-orders').textContent='Paczki ('+game.orders.filter(o=>['new','packed'].includes(o.status)).length+')';const pause=$('pause-live');$('mobile-pause').hidden=!(game.phase==='fulfill'||game.deliveries.length);$('mobile-pause').textContent=pause?.getAttribute('aria-pressed')==='true'?'▶':'Ⅱ';};
function reportAdvice(){const l=game.ledger,margin=E.round(l.sales-l.cogs-l.shipping-l.packaging-l.fees-l.refunds-l.returnFees),marketing=E.round(l.ads+l.agency);let text;if(!l.sales)text=game.lost?'Klienci trafili na brak towaru lub limit realizacji. Przed kolejną kampanią uzupełnij regały i sprawdź przepustowość.':'Brak wysłanej sprzedaży. Upewnij się, że towar dotarł, a gotowe paczki zostały przekazane kurierowi. Przy małym ruchu brak zakupu też jest możliwy.';else if(margin<0)text='Każda kolejna sprzedaż może pogłębiać stratę. Sprawdź cenę, rabat, gratisy i koszt dostawy w podglądzie koszyka.';else if(marketing>margin)text='Marketing kosztował więcej niż zostało po realizacji sprzedaży. Sprawdź kanały w Analityce; spróbuj mniejszego budżetu lub popraw marżę.';else if(E.profit(l)<0)text='Sprzedaż pokryła realizację i marketing, ale nie wszystkie koszty firmy. Sprawdź abonament, zatrudnienie i koszt finansowania.';else text='Ten dzień zakończył się zyskiem. Zachowaj rezerwę na zwroty i raty, a dopiero potem zwiększaj skalę.';return '<div class="report-advice"><strong>Co mówi wynik?</strong><p>'+text+'</p><div><span>Po realizacji i zwrotach</span><b>'+money(margin)+'</b></div><div><span>Marketing i agencja</span><b>'+money(marketing)+'</b></div></div>';}
document.addEventListener('change',e=>{if(e.target.id==='section-picker')go(e.target.value);});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;switch(b.id){case 'starter-kit':showDialog('<div class="eyebrow">ZESTAW NA START</div><h2>Dwa produkty, pierwsza kolekcja</h2><p>20 × Dewdrop: 1440 zł<br>20 × Cloud Nine: 1160 zł<br><b>Razem 2600 zł</b>. Dostawy po 1–5 minutach aktywnej gry, zapas zajmie 40 miejsc. Ceny początkowe: 179 i 149 zł. Kampanię wybierzesz osobno.</p><button id="confirm-starter" class="primary">Zamów zestaw za 2600 zł</button>');break;case 'confirm-starter':action(()=>{if(game.tutorial!==0||E.used(game)!==0)throw Error('Zestaw startowy jest dostępny tylko przed pierwszym zakupem.');const draft=JSON.parse(JSON.stringify(game));E.buy(draft,0,20);E.buy(draft,1,20);game=draft;closeDialog();tab='marketing';toast('Zestaw zamówiony. Teraz wybierz budżet marketingu.');});break;case 'guide-marketing':go('marketing');break;case 'guide-prices':go('products');break;case 'guide-analytics':go('analytics');break;case 'mobile-main':$('main-action').click();break;case 'mobile-orders':go('orders');break;case 'mobile-pause':$('pause-live').click();break;}});

let campaignPulseHTML='';
window.refreshCampaignPulse=function(){
const panel=$('campaign-pulse');if(!panel)return;
const rows=(E.config(game).channelStats||[]).filter(c=>c.id!=='organic'),sum=k=>rows.reduce((n,c)=>n+(c[k]||0),0),active=game.phase==='fulfill',remaining=Math.max(0,Math.ceil(((game.traffic?.duration||0)-(game.traffic?.elapsed||0))/1000)),queue=(game.live?.queue||[]).filter(o=>o.channel!=='organic').length;
const b=E.config(game),available=E.PRODUCTS.map((_,i)=>i).filter(i=>game.stock[i].qty>0||game.deliveries.some(d=>d.index===i));let forecast=0;
for(const c of E.CHANNELS)if(available.length)forecast+=E.reach(c.id,b.budgets[c.id])*available.reduce((n,i)=>n+E.conversion(game,i,c.cvr,E.audience(c.id,b.budgets[c.id])),0)/available.length;
const html=game.phase==='plan'?'<div><span class="eyebrow">MARKETING → KLIENCI → SPRZEDAŻ</span><h3>Twój plan: '+money(E.spend(game))+' na ruch i treści</h3><p>'+(available.length?'Potencjał reklam: około '+forecast.toFixed(0)+' zakupów przy obecnych cenach, przed ograniczeniem zapasu i realizacji. Wynik jest losowy.':'Wybierz towar, żeby zobaczyć potencjał sprzedaży kampanii.')+'</p></div><button class="secondary" data-tab="marketing">Dostosuj kampanię ↗</button>':'<div class="pulse-heading"><span class="eyebrow">EFEKTY REKLAM · DZISIAJ</span><strong>'+(active&&remaining?'● Ruch napływa · '+remaining+' s':active&&queue?'Klienci kończą zakupy':'Podsumowanie ruchu')+'</strong></div><div class="pulse-numbers">'+[['Wydano na kanały',money(sum('spend'))],['Wizyty z reklam',sum('visits')],['Zakupy przyjęte',sum('accepted')],['W kolejce do sklepu',queue],['Przychód wysłany',money(sum('sales'))]].map(([label,value])=>'<div><small>'+label+'</small><b>'+value+'</b></div>').join('')+'</div><p>Wartość przyjętych zamówień z reklam: <b>'+money(sum('orderedValue'))+'</b>. '+(sum('lost')?'Utracono '+sum('lost')+' zakupów: sprawdź zapasy i limit magazynu. ':queue?'Kolejne zamówienia pojawiają się co 10–50 sekund. ':'')+'Przychód pojawia się po wysyłce. Zysk uwzględnia też towar, agencję i koszty firmy.</p><div class="actions"><button class="secondary" data-tab="analytics">Porównaj kanały ↗</button>'+(active&&remaining&&b.budgets.google<=2950?'<button class="primary" data-boost="google">Google Ads +50 zł</button>':'')+'</div>';
if(html!==campaignPulseHTML){panel.innerHTML=html;campaignPulseHTML=html;}
};
