const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('./engine');
function closeDay(s,sales=0){E.openWithoutCampaign(s);s.cash=E.round(s.cash+sales);s.ledger.sales+=sales;s.total.sales+=sales;return E.close(s);}
function next(s){E.next(s);}
function rows(s,count=14,profit=100,sales=1000){s.history=Array.from({length:count},(_,i)=>({...s.ledger,day:i+1,profit,sales,orders:10,visits:100}));}
function grant(s){closeDay(s,60000);assert.equal(s.progression.goals[0].status,'completed');next(s);}
function unlockLoyalty(s){grant(s);closeDay(s,15000);assert.equal(s.progression.goals[1].status,'completed');next(s);}

test('Valuation needs seven closed days and ignores current ledger, grants and negative earnings',()=>{const s=E.create();assert.equal(E.valuation(s).ready,false);rows(s,6);assert.equal(E.valuation(s).value,0);rows(s,7);assert.equal(E.valuation(s).value,109500);s.ledger.sales=999999;assert.equal(E.valuation(s).value,109500);s.progression.grants=5000;assert.equal(E.valuation(s).value,109500);rows(s,14,-100);assert.equal(E.valuation(s).value,0);});
test('Quality and risk adjust valuation while monthly growth waits for sixty days',()=>{const s=E.create();rows(s,14);s.history.forEach(h=>h.channels=[{id:'google',sales:1000}]);const concentrated=E.valuation(s);s.history.forEach(h=>h.channels=[{id:'google',sales:500},{id:'meta',sales:500}]);assert.ok(E.valuation(s).value>concentrated.value);const healthy=E.valuation(s).value;s.cash=-1;assert.ok(E.valuation(s).value<healthy);s.cash=10000;rows(s,59);assert.equal(E.valuation(s).growth,null);rows(s,60);s.history.slice(-30).forEach(h=>h.sales=2000);assert.equal(E.valuation(s).growth,1);assert.ok(E.valuation(s).parts.some(p=>p.label.includes('Wzrost')));});
test('Grant is paid exactly once at close and reconciles cash without inflating profit or sales',()=>{const s=E.create();const h=closeDay(s,60000);assert.equal(s.progression.grants,5000);assert.equal(h.goalEvents[0].id,'launch');assert.equal(h.cash,s.cash);assert.equal(s.total.sales,60000);assert.equal(E.cashBridge(s).gap,0);assert.equal(s.progression.goals[1].startDay,2);assert.equal(s.progression.goals.filter(g=>g.status==='active').length,1);assert.ok(E.validate(s));const loaded=E.migrate(JSON.parse(JSON.stringify(s)));assert.equal(loaded.cash,s.cash);assert.equal(loaded.progression.grants,5000);assert.throws(()=>E.close(loaded));next(loaded);closeDay(loaded);assert.equal(loaded.progression.grants,5000);assert.equal(E.cashBridge(loaded).gap,0);});
test('Revenue target needs positive P&L; historical sales count after safe migration',()=>{const s=E.create();delete s.progression;rows(s,7,100,10000);assert.ok(E.validate(s));E.migrate(s);assert.equal(s.progression.grants,0);s.total.cogs=100000;closeDay(s);assert.equal(s.progression.goals[0].status,'active');next(s);closeDay(s,150000);assert.equal(s.progression.grants,5000);});
test('Timed target excludes previous profit, fails after exactly fourteen days and can restart',()=>{const s=E.create();grant(s);for(let i=0;i<14;i++){closeDay(s);assert.equal(s.progression.goals[1].status,i===13?'failed':'active');if(i<13)next(s);}assert.throws(()=>E.retryGoal(s));next(s);E.retryGoal(s);assert.equal(s.progression.goals[1].startDay,s.day);assert.equal(s.progression.goals[1].attempt,2);closeDay(s,15000);assert.ok(s.progression.unlocks.includes('preferentialLoan'));assert.equal(E.debt(s),0);assert.equal(s.progression.grants,5000);assert.ok(E.validate(s));});
test('Six goals complete in order, future rewards are hooks and valuation milestones remain earned',()=>{const s=E.create();unlockLoyalty(s);s.crm.customers.c1={shippedOrders:2,acquisitionDay:1,lastShippedDay:1,nextPurchaseDay:1,netRevenue:10000,contribution:1000};closeDay(s);assert.ok(s.progression.unlocks.includes('winback'));next(s);while(s.history.length<6){closeDay(s,30000);next(s);}for(const key of ['warehouse','privateLabel','endgame']){closeDay(s,30000);assert.ok(s.progression.unlocks.includes(key));next(s);}assert.equal(s.progression.goals.filter(g=>g.status==='completed').length,6);assert.equal(s.progression.goals.filter(g=>g.status==='active').length,0);assert.equal(s.progression.stage,6);s.level=1;s.shipped=0;const beforeMove=s.cash;E.upgrade(s);assert.equal(s.level,2);assert.equal(s.cash,E.round(beforeMove-6000));s.history.forEach(h=>h.profit=-100);closeDay(s);assert.equal(E.valuation(s).value,0);assert.equal(s.progression.goals[5].status,'completed');});
test('Save validation rejects duplicate rewards and broken progression; bankruptcy prevents retry',()=>{const s=E.create();assert.ok(E.validate(s));s.progression.grants=5000;assert.equal(E.validate(s),false);s.progression.grants=0;s.progression.goals[2].status='active';assert.equal(E.validate(s),false);const b=E.create();b.cash=-100;E.bankrupt(b);assert.throws(()=>E.retryGoal(b));});
test('Generic goal metrics support AOV and consecutive ROAS/LTV:CAC days with null resets',()=>{const s=E.create();rows(s,3);s.history.forEach(h=>{h.productSales=3000;h.roas=4;h.ltvCac=3;});const state={startDay:1};assert.equal(E.goalProgress(s,{type:'aov',windowDays:null},state),300);assert.equal(E.goalProgress(s,{type:'roasStreak',metricThreshold:3,windowDays:null},state),3);s.history[1].roas=null;assert.equal(E.goalProgress(s,{type:'roasStreak',metricThreshold:3,windowDays:null},state),1);});
