import * as T from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {clone} from './vendor/SkeletonUtils.js';
const scene=new T.Scene();scene.background=new T.Color('#22252c');scene.fog=new T.Fog('#22252c',18,40);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;document.body.prepend(renderer.domElement);const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,60);camera.position.set(7,5.6,8);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,0);controls.enableDamping=true;controls.maxPolarAngle=1.45;controls.minDistance=3;controls.maxDistance=22;scene.add(new T.HemisphereLight(0xd2e1ff,0x584737,2));const sun=new T.DirectionalLight(0xffe1b1,4);sun.position.set(3,9,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9});sun.shadow.bias=-.0002;scene.add(sun);
function box(w,h,d,x,y,z,color){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.82}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}box(16,.15,13,0,-.09,0,'#625d54');const grid=new T.GridHelper(16,32,0x797267,0x6a645b);grid.position.y=.002;scene.add(grid);box(3.2,.14,1.55,0,1.08,0,'#af8052');for(const x of [-1.4,1.4])for(const z of [-.6,.6])box(.09,1,.09,x,.5,z,'#252930');box(2.9,.07,1.3,0,.2,0,'#49413b');for(const x of [-.9,.1,.85]){box(.45,.36,.38,x,1.33,.1,'#b18b59');box(.08,.01,.39,x,1.515,.1,'#e8c790');}for(let j=0;j<3;j++){const x=-3+j*3;box(2.2,.08,.6,x,1.2,-4,'#46454a');box(2.2,.08,.6,x,2.1,-4,'#46454a');for(const dx of [-1.05,1.05])box(.08,2.3,.08,x+dx,1.15,-4,'#6c3b42');for(let k=0;k<5;k++)box(.25,.4,.3,x-.8+k*.4,1.43,-4,'#a88770');}
const pts=[[-2.7,0,-1.9],[2.7,0,-1.9],[3.5,0,-1.1],[3.5,0,1.1],[2.7,0,1.9],[-2.7,0,1.9],[-3.5,0,1.1],[-3.5,0,-1.1]].map(p=>new T.Vector3(...p));const curve=new T.CatmullRomCurve3(pts,true,'centripetal');const length=curve.getLength();const line=new T.LineLoop(new T.BufferGeometry().setFromPoints(curve.getPoints(240)),new T.LineBasicMaterial({color:0xe74e69}));line.position.y=.02;line.visible=false;scene.add(line);
let paused=false,actors=[],distance=0,loaded=false,closeup=false;const q=new T.Quaternion(),v=new T.Vector3();
function bones(root){const out=[];root.traverse(x=>{if(x.isBone)out.push(x);});return out;}
function pose(g){const m=new T.AnimationMixer(g.scene);m.clipAction(g.animations.find(a=>a.name==='TPose')).play();m.setTime(0);g.scene.updateMatrixWorld(true);return m;}
function retarget(g,source,name){const sm=pose(source);pose(g);const sb=bones(source.scene),tb=bones(g.scene),map=new Map(sb.map(b=>[b.name,b]));const restS=new Map(sb.map(b=>[b.name,b.getWorldQuaternion(new T.Quaternion()).invert()]));const restT=new Map(tb.map(b=>[b.name,b.getWorldQuaternion(new T.Quaternion())]));const hip=tb.find(b=>/Hips$/.test(b.name)),sourceHip=sb.find(b=>/Hips$/.test(b.name));const hipBase=hip.position.clone(),sourceBase=sourceHip.getWorldPosition(new T.Vector3());const parentScale=hip.parent.getWorldScale(new T.Vector3()).y;sm.stopAllAction();const src=source.animations.find(a=>a.name===name);sm.clipAction(src).play();const times=[],values=new Map(tb.map(b=>[b.name,[]])),hipValues=[];for(let f=0;f<=Math.ceil(src.duration*60);f++){const t=Math.min(src.duration,f/60);times.push(t);sm.setTime(t);source.scene.updateMatrixWorld(true);for(const b of tb){const orig=map.get(b.name);if(!orig)continue;const world=orig.getWorldQuaternion(new T.Quaternion()).multiply(restS.get(b.name)).multiply(restT.get(b.name));const parent=b.parent.getWorldQuaternion(new T.Quaternion()).invert();b.quaternion.copy(parent.multiply(world));b.updateMatrixWorld(true);values.get(b.name).push(...b.quaternion.toArray());}const dy=sourceHip.getWorldPosition(new T.Vector3()).y-sourceBase.y;hipValues.push(hipBase.x,hipBase.y+dy/parentScale,hipBase.z);}const tracks=tb.filter(b=>values.get(b.name).length).map(b=>new T.QuaternionKeyframeTrack(b.name+'.quaternion',times,values.get(b.name)));tracks.push(new T.VectorKeyframeTrack(hip.name+'.position',times,hipValues));return new T.AnimationClip(name,src.duration,tracks);}
try{const loader=new GLTFLoader();const [female,source]=await Promise.all([loader.loadAsync('./employee.glb'),loader.loadAsync('./motion-source.glb')]);source.scene.rotation.y+=Math.PI;const walk=retarget(female,source,'Walk');pose(female);const bbox=new T.Box3().setFromObject(female.scene),size=bbox.getSize(new T.Vector3()),factor=1.72/size.y;const template=female.scene;template.scale.multiplyScalar(factor);template.updateMatrixWorld(true);const floor=new T.Box3().setFromObject(template).min.y;template.position.y-=floor;template.traverse(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true;}});function setCount(n){for(const a of actors)scene.remove(a.root);actors=[];for(let i=0;i<n;i++){const model=clone(template),root=new T.Group();root.add(model);scene.add(root);const mixer=new T.AnimationMixer(model),action=mixer.clipAction(walk);action.play();actors.push({root,model,mixer,action,offset:(i/n+.32)%1});}distance=0;}setCount(1);document.getElementById('count').onchange=e=>setCount(+e.target.value);document.getElementById('loading').hidden=true;loaded=true;window.preview={actors:()=>actors,curve,length,walk,stats:()=>({loaded,count:actors.length,paused,distance})};}catch(e){document.getElementById('loading').textContent='Nie udało się załadować podglądu: '+e.message;console.error(e);}
document.getElementById('pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Wznów':'Pauza';};document.getElementById('routes').onclick=e=>{line.visible=!line.visible;e.target.classList.toggle('active',line.visible);};document.getElementById('camera').onclick=e=>{closeup=!closeup;e.target.textContent=closeup?'Cała scena':'Zbliżenie';if(!closeup){camera.position.set(7,5.6,8);controls.target.set(0,1,0);}};function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();const clock=new T.Clock();function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(loaded){if(!paused)distance+=dt*.95;for(const a of actors){const u=(distance/length+a.offset)%1,p=curve.getPointAt(u),dir=curve.getTangentAt(u);a.root.position.copy(p);a.root.rotation.y=Math.atan2(dir.x,dir.z);a.mixer.setTime((distance/1.46* a.action.getClip().duration+a.offset*a.action.getClip().duration)%a.action.getClip().duration);}if(closeup){const p=actors[0].root.position;controls.target.lerp(new T.Vector3(p.x,1,p.z),.1);camera.position.lerp(new T.Vector3(p.x+3.1,2.7,p.z+4),.06);}document.getElementById('status').textContent=paused?'Pauza · obejrzyj pozę z każdej strony':actors.length+' pracownic · płynny obrót · odstępy na trasie';}controls.update();renderer.render(scene,camera);}frame();


