import * as T from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {clone} from './vendor/SkeletonUtils.js';
const stage=document.getElementById('stage'),scene=new T.Scene();
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;stage.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(40,1,.1,70),shopCamera=new T.OrthographicCamera(-8.75,8.75,4.895,-4.895,.1,70);shopCamera.position.set(0,8,11);shopCamera.lookAt(0,0,0);camera.position.set(7,5.6,10);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,1);controls.enableDamping=true;controls.maxPolarAngle=1.45;controls.minDistance=3;controls.maxDistance=24;controls.enabled=false;
scene.add(new T.HemisphereLight(0xdbe0ef,0x706057,2.6));const sun=new T.DirectionalLight(0xffdfba,3);sun.position.set(-3,9,-2);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10});sun.shadow.bias=-.0002;scene.add(sun);const fill=new T.DirectionalLight(0xe5e9ff,1.6);fill.position.set(0,5,8);scene.add(fill);
const props=new T.Group();props.visible=false;scene.add(props);
function box(w,h,d,x,y,z,color){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.85}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;props.add(m);return m;}
box(18,.15,14,0,-.1,0,'#61584e');box(4.7,.14,2.5,.45,1.15,.6,'#a57d4e');for(const x of [-1.7,2.6])for(const z of [-.5,1.65])box(.1,1.1,.1,x,.55,z,'#252930');box(4.4,.09,2.3,.45,.22,.6,'#594d3e');for(const x of [-.9,.3,1.4])box(.5,.35,.4,x,1.4,.6,'#b68a57');for(let j=0;j<4;j++){const x=-5+j*3;for(const y of [.5,1.3,2.1]){box(2.4,.08,.7,x,y,-4.9,'#303034');for(let k=0;k<5;k++)box(.28,.42,.35,x-.8+k*.4,y+.25,-4.9,'#b09675');}for(const dx of [-1.15,1.15])box(.08,2.4,.08,x+dx,1.2,-4.9,'#762f3a');}
const occluder=new T.Mesh(new T.BoxGeometry(4.7,1.17,2.5),new T.MeshBasicMaterial({colorWrite:false,depthWrite:true}));occluder.position.set(.45,.585,.6);occluder.renderOrder=-10;scene.add(occluder);
const shadow=new T.Mesh(new T.PlaneGeometry(18,14),new T.ShadowMaterial({opacity:.24}));shadow.rotation.x=-Math.PI/2;shadow.receiveShadow=true;shadow.position.y=-.006;scene.add(shadow);
// Each zone has an open aisle, not a closed lap. Workers choose a new station after a dwell.
const zones=[
 {name:'Regały po lewej',points:[[-3.35,-2.8],[-3.35,-.2],[-3.35,1.6],[-2.7,2.35]],labels:['Pobieranie produktu','Kontrola produktu','Przygotowanie paczki','Przekazanie do pakowania']},
 {name:'Dostawy i odbiór',points:[[4.05,-2.2],[4.05,.3],[4.8,1.65],[5.7,1.65]],labels:['Przyjęcie dostawy','Kontrola produktu','Przygotowanie wysyłki','Odbiór paczek']},
 {name:'Stanowisko pakowania',points:[[-2.25,3.25],[-1.1,3.25],[-.2,3.25],[-.2,4.25]],labels:['Pobranie opakowania','Przygotowanie paczki','Sprawdzenie etykiety','Odłożenie paczki']},
 {name:'Strefa wysyłki',points:[[1.05,3.45],[2.25,3.45],[3.5,3.45],[3.5,4.65]],labels:['Kontrola paczki','Sortowanie przesyłek','Etykietowanie','Przygotowanie odbioru']},
 {name:'Zaplecze magazynu',points:[[-1.45,-1.7],[.1,-1.7],[1.5,-1.7],[2.65,-1.9]],labels:['Sprawdzenie stanów','Pobranie produktu','Kontrola partii','Odkładanie towaru']}
].map(z=>({...z,points:z.points.map(([x,z])=>new T.Vector3(x,0,z))}));
const routes=new T.Group();routes.visible=false;scene.add(routes);const colors=[0xff8f7c,0xeac175,0xd9708d,0x8dafba,0xc8acd6];zones.forEach((z,i)=>{const line=new T.Line(new T.BufferGeometry().setFromPoints(z.points),new T.LineBasicMaterial({color:colors[i]}));line.position.y=.015;routes.add(line);for(const p of z.points){const dot=new T.Mesh(new T.CircleGeometry(.12,20),new T.MeshBasicMaterial({color:colors[i]}));dot.rotation.x=-Math.PI/2;dot.position.copy(p);dot.position.y=.02;routes.add(dot);}});
let actors=[],paused=false,loaded=false,shop=true,closeup=false,elapsed=0,walk,idle;
function bones(root){const out=[];root.traverse(x=>{if(x.isBone)out.push(x);});return out;}
const mapping={pelvis:'Hips',spine_01:'Spine',spine_02:'Spine1',spine_03:'Spine2',neck_01:'Neck',Head:'Head'};for(const [s,side] of [['l','Left'],['r','Right']]){for(const [a,b] of Object.entries({clavicle:'Shoulder',upperarm:'Arm',lowerarm:'ForeArm',hand:'Hand',thigh:'UpLeg',calf:'Leg',foot:'Foot',ball:'ToeBase'}))mapping[a+'_'+s]=side+b;for(const [a,b] of Object.entries({thumb:'Thumb',index:'Index',middle:'Middle',ring:'Ring',pinky:'Pinky'}))for(let n=1;n<=3;n++)mapping[a+'_0'+n+'_'+s]=side+'Hand'+b+n;}
function retarget(target,source,name){const sm=new T.AnimationMixer(source.scene);sm.clipAction(source.animations.find(a=>a.name==='TPose')).play();sm.setTime(0);source.scene.updateMatrixWorld(true);const sb=bones(source.scene),tb=bones(target),map=new Map(sb.map(b=>[b.name.replace(/^mixamorig:?/,''),b]));const base=tb.map(b=>[b,b.position.clone(),b.quaternion.clone()]);target.updateMatrixWorld(true);const restS=new Map(sb.map(b=>[b,b.getWorldQuaternion(new T.Quaternion()).invert()])),restT=new Map(tb.map(b=>[b,b.getWorldQuaternion(new T.Quaternion())]));const hip=tb.find(b=>b.name==='pelvis'),sh=map.get('Hips'),hipBase=hip.position.clone(),sy=sh.getWorldPosition(new T.Vector3()).y;const inverseHipParent=hip.parent.matrixWorld.clone().invert();const parentY=new T.Vector3(0,1,0).transformDirection(inverseHipParent);sm.stopAllAction();const clip=source.animations.find(a=>a.name===name);sm.clipAction(clip).play();const times=[],values=new Map(tb.map(b=>[b,[]])),hipValues=[];
for(let f=0;f<=Math.ceil(clip.duration*60);f++){const t=Math.min(clip.duration,f/60);times.push(t);sm.setTime(t);source.scene.updateMatrixWorld(true);for(const b of tb){const orig=map.get(mapping[b.name]);if(!orig)continue;const world=orig.getWorldQuaternion(new T.Quaternion()).multiply(restS.get(orig)).multiply(restT.get(b));b.quaternion.copy(b.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(world));b.updateMatrixWorld(true);values.get(b).push(...b.quaternion.toArray());}const dy=sh.getWorldPosition(new T.Vector3()).y-sy;hipValues.push(...hipBase.clone().addScaledVector(parentY,dy).toArray());}
const tracks=tb.filter(b=>values.get(b).length).map(b=>new T.QuaternionKeyframeTrack(b.name+'.quaternion',times,values.get(b)));tracks.push(new T.VectorKeyframeTrack('pelvis.position',times,hipValues));for(const [b,p,q] of base){b.position.copy(p);b.quaternion.copy(q);}target.updateMatrixWorld(true);return new T.AnimationClip(name,clip.duration,tracks);}
function relaxedIdle(root){const all=bones(root),base=all.map(b=>[b,b.quaternion.clone(),b.position.clone()]);root.updateMatrixWorld(true);for(const [name,angle] of [['upperarm_l',-1.4],['upperarm_r',1.4]]){const b=root.getObjectByName(name);const world=b.getWorldQuaternion(new T.Quaternion()).premultiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),angle));b.quaternion.copy(b.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(world));b.updateMatrixWorld(true);}const times=[0,1.5,3],tracks=[];for(const b of all){const q=b.quaternion.clone(),mid=q.clone();if(b.name==='spine_03')mid.multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),.012));tracks.push(new T.QuaternionKeyframeTrack(b.name+'.quaternion',times,[...q.toArray(),...mid.toArray(),...q.toArray()]));}const hip=root.getObjectByName('pelvis');tracks.push(new T.VectorKeyframeTrack('pelvis.position',times,[...hip.position.toArray(),...hip.position.toArray(),...hip.position.toArray()]));for(const [b,q,p] of base){b.quaternion.copy(q);b.position.copy(p);}root.updateMatrixWorld(true);return new T.AnimationClip('Standing',3,tracks);}
function addShoes(root){root.updateMatrixWorld(true);for(const side of ['l','r']){const foot=root.getObjectByName('foot_'+side),toe=root.getObjectByName('ball_'+side);const center=foot.getWorldPosition(new T.Vector3()).lerp(toe.getWorldPosition(new T.Vector3()),.75);center.y=.045;const shoe=new T.Mesh(new T.SphereGeometry(1,16,10),new T.MeshStandardMaterial({color:'#34363b',roughness:.95}));shoe.position.copy(center);shoe.scale.set(.06,.045,.145);shoe.userData.sole=true;scene.add(shoe);foot.attach(shoe);}}
function tailor(mesh){mesh.material[2]=mesh.material[1];mesh.material[1].onBeforeCompile=shader=>{shader.vertexShader='varying float tailorY;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n tailorY=position.y;');shader.fragmentShader='varying float tailorY;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n if(tailorY<0.98)diffuseColor.rgb=vec3(0.029,0.034,0.047);');};}
function dress(root){root.traverse(mesh=>{if(!mesh.isSkinnedMesh||mesh.name!=='Superhero_Female')return;const g=mesh.geometry,skin=g.attributes.skinIndex,weight=g.attributes.skinWeight,pos=g.attributes.position,idx=g.index;const fabric=new T.MeshStandardMaterial({color:'#62323f',roughness:1}),pants=new T.MeshStandardMaterial({color:'#30343d',roughness:1}),shoes=new T.MeshStandardMaterial({color:'#242327',roughness:.95});mesh.material.color.setRGB(1.2,1.12,1.08);mesh.material.roughness=.8;mesh.material.normalScale.set(.5,.5);mesh.material=[mesh.material,fabric,pants,shoes];g.clearGroups();let start=0,previous=-1;for(let i=0;i<idx.count;i+=3){let y=0,skinScore=0,foot=0,leg=0;for(let j=0;j<3;j++){const v=idx.getX(i+j);y+=pos.getY(v)/3;for(let k=0;k<4;k++){const name=mesh.skeleton.bones[skin.getComponent(v,k)]?.name||'',w=weight.getComponent(v,k)/3;if(/Head|neck|hand|thumb|index|middle|ring|pinky/.test(name))skinScore+=w;if(/foot|ball/.test(name))foot+=w;if(/thigh|calf|foot|ball/.test(name))leg+=w;}}const mat=skinScore>.45?0:foot>.5?3:(leg>.45||y<.94)?2:1;if(mat!==previous){if(previous>=0)g.addGroup(start,i-start,previous);start=i;previous=mat;}}g.addGroup(start,idx.count-start,previous);mesh.userData.uniform=true;});}
try{const loader=new GLTFLoader();const [female,source,hair]=await Promise.all([loader.loadAsync('./character/Superhero_Female_FullBody.gltf'),loader.loadAsync('./motion-source.glb'),loader.loadAsync('./character/Hair_Long.gltf')]);female.scene.updateMatrixWorld(true);const head=female.scene.getObjectByName('Head');scene.add(hair.scene);head.attach(hair.scene);hair.scene.traverse(m=>{if(m.isMesh){m.material.color.set('#a6774f');m.material.roughness=.9;m.material.alphaTest=.35;}});source.scene.rotation.y+=Math.PI;walk=retarget(female.scene,source,'Walk');idle=relaxedIdle(female.scene);dress(female.scene);addShoes(female.scene);const size=new T.Box3().setFromObject(female.scene).getSize(new T.Vector3());female.scene.scale.multiplyScalar(1.72/size.y);female.scene.updateMatrixWorld(true);female.scene.position.y-=new T.Box3().setFromObject(female.scene).min.y;female.scene.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;}});
function setCount(n){actors.forEach(a=>scene.remove(a.root));actors=[];for(let i=0;i<n;i++){const model=clone(female.scene),root=new T.Group();root.add(model);scene.add(root);model.traverse(m=>{if(m.userData.uniform){m.material=m.material.map(x=>x.clone());m.material[1].color.set(['#633440','#3c4550','#55464c','#42504c','#534357'][i]);tailor(m);}});const mixer=new T.AnimationMixer(model),wa=mixer.clipAction(walk).play(),ia=mixer.clipAction(idle).play();wa.setEffectiveWeight(0);ia.setEffectiveWeight(1);const zone=zones[i],node=i%4;root.position.copy(zone.points[node]);const a={root,model,mixer,wa,ia,zone,node,goal:node,next:node,wait:1+i*.7,speed:0,stride:0,blend:0,visits:0};actors.push(a);}elapsed=0;}
setCount(3);document.getElementById('count').onchange=e=>setCount(+e.target.value);document.getElementById('loading').hidden=true;loaded=true;window.preview={actors:()=>actors,zones,walk,step:dt=>update(dt),stats:()=>({loaded,count:actors.length,paused,elapsed,shop})};}catch(e){document.getElementById('loading').textContent='Nie udało się załadować podglądu: '+e.message;console.error(e);}
function choose(a){let goal=Math.floor(Math.random()*a.zone.points.length);if(goal===a.node)goal=(goal+1)%a.zone.points.length;a.goal=goal;a.next=a.node+Math.sign(goal-a.node);}
const targetQ=new T.Quaternion(),axis=new T.Vector3(0,1,0);
function update(dt){if(paused||!loaded)return;elapsed+=dt;for(const a of actors){let traveled=0;if(a.wait>0){a.wait-=dt;if(a.wait<=0)choose(a);}else{const target=a.zone.points[a.next],delta=target.clone().sub(a.root.position),dist=delta.length();targetQ.setFromAxisAngle(axis,Math.atan2(delta.x,delta.z));const angle=a.root.quaternion.angleTo(targetQ);a.root.quaternion.rotateTowards(targetQ,dt*2.8);const desired=angle>.18?0:Math.min(.84,Math.sqrt(1.4*dist));a.speed=T.MathUtils.damp(a.speed,desired,5,dt);traveled=angle>.18?0:Math.min(dist,a.speed*dt);const candidate=a.root.position.clone().addScaledVector(delta.normalize(),traveled);if(actors.some(other=>other!==a&&other.root.position.distanceTo(candidate)<.7)){traveled=0;a.speed=0;}else a.root.position.copy(candidate);if(dist<.045){a.root.position.copy(target);a.node=a.next;a.speed=0;if(a.node===a.goal){a.wait=2+Math.random()*4;a.visits++;}else{a.next=a.node+Math.sign(a.goal-a.node);}}}
a.stride+=traveled;a.blend=T.MathUtils.damp(a.blend,traveled>0?Math.min(1,a.speed/.45):0,10,dt);a.wa.time=(a.stride/1.54*walk.duration)%walk.duration;a.ia.time=(elapsed+iPhase(a))%idle.duration;a.wa.setEffectiveWeight(a.blend);a.ia.setEffectiveWeight(1-a.blend);a.mixer.update(0);a.root.updateMatrixWorld(true);if(!a.soles){a.soles=[];a.model.traverse(m=>{if(m.userData.sole)a.soles.push(m);});}const lowest=Math.min(...a.soles.map(m=>new T.Box3().setFromObject(m).min.y));a.model.position.y-=lowest;}}
function iPhase(a){return actors.indexOf(a)*.63;}
document.getElementById('pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Wznów':'Pauza';};document.getElementById('routes').onclick=e=>{routes.visible=!routes.visible;e.target.classList.toggle('active',routes.visible);};
function setView(){props.visible=!shop;shadow.visible=shop;occluder.visible=shop;scene.background=shop?null:new T.Color('#25272b');stage.classList.toggle('shop',shop);controls.enabled=!shop;document.getElementById('view').textContent=shop?'Obejrzyj w 3D':'Na tle sklepu';document.getElementById('camera').disabled=shop;closeup=false;resize();}
document.getElementById('view').onclick=()=>{shop=!shop;setView();};document.getElementById('camera').onclick=e=>{closeup=!closeup;e.target.textContent=closeup?'Cała scena':'Zbliżenie';if(!closeup){camera.position.set(7,5.6,10);controls.target.set(0,1,1);}};
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize);setView();const clock=new T.Clock();function frame(){requestAnimationFrame(frame);update(Math.min(clock.getDelta(),.05));if(closeup&&actors[0]){const p=actors[0].root.position;controls.target.lerp(new T.Vector3(p.x,1,p.z),.12);camera.position.lerp(new T.Vector3(p.x+2.5,2.4,p.z+3.5),.07);}if(loaded){const working=actors.filter(a=>a.wait>0).length;document.getElementById('status').textContent=paused?'Pauza':`${actors.length} pracownice · ${working} przy stanowiskach · ${actors.length-working} w drodze`;}controls.update();renderer.render(scene,shop?shopCamera:camera);}frame();

